#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist mysqld.success

echo "install dovecot from apt" | log
packages=(dovecot-imapd dovecot-pop3d dovecot-mysql dovecot-sieve dovecot-lmtpd)
apt install -y "${packages[@]}" | log
checkPackageInstalled "${packages[@]}"

tagScript success
exit 0