#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Running Plesk Official Installer" | log
sh <(curl https://autoinstall.plesk.com/one-click-installer || wget -O - https://autoinstall.plesk.com/one-click-installer) | log
waitOrStop 0
server_ip=`hostname -I | xargs`
first_login=`grep "${serverip}:8443" $(rootDir)/temp/*.log | rev | cut -d ' ' -f 1 | rev`

descriptionAppend "To complete the configuration process, browse this URL:"
descriptionAppend "${first_login}"
descriptionAppend " "

tagScript success

exit 0
