#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

echo "Checking resolve.conf contents"

FILE="/etc/resolv.conf"
NAMESERVER1="nameserver 8.8.8.8"
NAMESERVER2="nameserver 8.8.4.4"

if ! grep -q "$NAMESERVER1" $FILE; then
  echo "$NAMESERVER1" | sudo tee -a $FILE
fi

if ! grep -q "$NAMESERVER2" $FILE; then
  echo "$NAMESERVER2" | sudo tee -a $FILE
fi
