#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck
checkTagExist apache2.success
checkTagExist php-fpm.success

echo "Tweaking apache to work with php-fpm" | log
phpVersion=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")
a2enmod proxy_fcgi setenvif
# a2enmod actions fastcgi alias
# a2enmod actions fastcgi alias proxy_fcgi
a2enconf php$phpVersion-fpm
sed  -i 's|.*SetHandler.*|SetHandler "proxy:fcgi://localhost:9000/"|'  /etc/apache2/conf-enabled/php$phpVersion-fpm.conf

systemctl restart apache2.service

tagScript success

exit 0
