#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck
checkTagExist apache2.success
checkTagExist php-fpm.success

rootDir=$(rootDir)
phpVersion=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")

echo "Tweaking apache to work with php-fpm" | log

a2enmod actions fastcgi alias proxy_fcgi

cp $rootDir/tweaks/extras/lamp/000-default.conf /etc/apache2/sites-available/

if [ -f "$rootDir/temp/apache-enable-ssl.success" ];
then
    tweakFilePath=$rootDir/tweaks/extras/lamp/default-ssl-customize
    perl -i -p0e 's/\t#FPM_INSTALL_PLACEHOLDER/`cat $ARGV[0]`/se' -- /etc/apache2/sites-available/default-ssl.conf "$tweakFilePath"
fi

systemctl restart apache2.service

tagScript success

exit 0
