#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist apache2.success

echo "Restarting apache service" | log
systemctl restart apache2.service
systemctl enable apache2.service
waitOrStop 0 "Restart apache service failed"

tagScript success

exit 0