#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist apache2.success

certsPath=/etc/letsencrypt/live/${CWM_DOMAIN}

echo "Creating SSL params" | log
cat << EOF >> /etc/apache2/conf-available/ssl-params.conf
SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLHonorCipherOrder On
Header always set X-Frame-Options DENY
Header always set X-Content-Type-Options nosniff
# Requires Apache >= 2.4
SSLCompression off
SSLUseStapling on
SSLStaplingCache "shmcb:logs/stapling-cache(150000)"
# Requires Apache >= 2.4.11
SSLSessionTickets Off
EOF

## applying ssl for cc web app ##
systemctl stop apache2.service
execSpecial 3 '(fail|error)' certbot certonly -n --standalone --preferred-challenges http --agree-tos --email ${ADMINEMAIL} -d ${CWM_DOMAIN} ${CWM_DEBUG:+"--test-cert"}

if [[ $? == 1 ]]; then
	export certbot_failed=1
	echo "Generating self-signed certificate" | log
	#waitOrStop 0 "Failed certbot certificate generation"
	mkdir /etc/letsencrypt/live
	mkdir /etc/letsencrypt/live/${CWM_DOMAIN}
	openssl req -x509 -sha256 -newkey rsa:2048 -keyout /etc/letsencrypt/live/${CWM_DOMAIN}/privkey.pem -out /etc/letsencrypt/live/${CWM_DOMAIN}/fullchain.pem -days 1024 -nodes -subj '/CN=localhost'
	waitOrStop 0 "Certificate creation failed"

	# Sending log to log server - 45-93-93-142.cloud-xip.com
	curl -v -X POST -D -H "Content-Type: application/x-www-form-urlencoded" -d "vm_name='$CWM_NAME'&image_name='$CWM_OS'&vm_owner='$ADMINEMAIL'" http://45-93-93-142.cloud-xip.com

else	
	export certbot_failed=0
fi

echo "Tweaking SSL virtual host" | log
defaultSSL=/etc/apache2/sites-available/default-ssl.conf
sed -i '/ServerAdmin/s/webmaster@localhost/'"${ADMINEMAIL}"'/g' $defaultSSL
sed -i '/SSLCertificateFile/s/\/etc\/ssl\/certs\/ssl-cert-snakeoil.pem/'"${certsPath//\//\\/}"'\/fullchain.pem/g' $defaultSSL
sed -i '/SSLCertificateKeyFile/s/\/etc\/ssl\/private\/ssl-cert-snakeoil.key/'"${certsPath//\//\\/}"'\/privkey.pem/g' $defaultSSL
# add ServerName + fpm install placeholder
sed -i '/<VirtualHost/{ :a N;/<\/VirtualHost>/!b a; /ServerName/!s!\([[:blank:]]*\)\(</VirtualHost>\)!\1\tServerName localhost\n\t\tServerAlias '"${CWM_DOMAIN}"'\n\t\t#FPM_INSTALL_PLACEHOLDER\n\1\2!}' $defaultSSL


echo "Enabling apache ssl modules" | log
a2enmod ssl
a2enmod headers
a2enconf ssl-params
a2ensite default-ssl

echo "Restarting apache service" | log
systemctl restart apache2.service
waitOrStop 0 "Restart apache service failed"

descriptionAppend "SSL certificates location: ${certsPath}"
descriptionAppend " "

tagScript success

exit 0
