#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

#TODO Proper directory location 
EXTRAS_DIR="/opt/installer/tweaks/extras/"

cp "$EXTRAS_DIR/autoremove-old-logs/cwm-logcleaner" /etc/cron.daily/

tagScript success
