#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Updating and upgrading OS to latest kernel and packages" | log
yum update -y | log
yum upgrade -y | log
yum autoremove -y | log

history -c | log

tagScript success

exit 0
