#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing certbot" | log
installPackage software-properties-common
waitOrStop 0 "Failed apt install: software-properties-common"
add-apt-repository universe
add-apt-repository -r ppa:certbot/certbot
apt update
installPackage certbot
waitOrStop 0 "Failed apt install: certbot"

# tag ssl-ready.success
tagScript success

exit 0
