#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist wp-cli.success
checkTagExist nginx-certbot.success

### install certificate on a wordpress domain ###
domain=$(wp option get siteurl --allow-root --path /var/www/html/)
certbot --nginx --quiet --redirect -d $domain | log

tag certbot-nginx-wordpress.success
tagScript success
