#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

cronFilename=/etc/cron.daily/installer-autoremove-old-logs
minSpaceLeftKbytes=1000000
minLogSizeKbytes=10000

if [ -f "$cronFilename" ]; then
    echo "cron file already installed. Skipping." | log
    exit 99
fi

cat << EOF > ${cronFilename}
#!/bin/bash

availablespace="\$(df / | awk 'NR==2{print \$4}')"

if [ "\$availablespace" -gt "${minSpaceLeftKbytes}" ]; then
    exit 0
fi

# Generate list of large files in log directories
largeFilesList="\$(find /var/log/ -type f -size +${minLogSizeKbytes}k | sort | xargs -r file)"

if [ -z "\$largeFilesList" ]; then
    exit 0
fi

# Find text files and empty them
textFiles="\$(printf "\$largeFilesList" | tr ':' ' ' | grep -i text)"
printf "\$textFiles" | awk '{ print "emptying "\$1 }'
printf "\$textFiles" | awk '{ print \$1 }' | xargs -r truncate --size 0

# Find gzipped log files and remove them
gzipFiles="\$(printf "\$largeFilesList" | tr ':' ' ' | grep -i gzip)"
printf "\$gzipFiles" | awk '{ print "deleting "\$1 }'
printf "\$gzipFiles" | awk '{ print \$1 }' | xargs -r rm -f

exit 0

EOF
chmod +x $cronFilename

tagScript success

exit 0
