#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

cronFilename=/etc/cron.daily/installer-autoremove-old-logs

if [ ! -f "$cronFilename" ];
then
    echo "#!/bin/bash" > $cronFilename
    echo "df / | tail -1 | awk '{ if (\$4 < 2097152) print \"find /var/log -type f  | xargs file | grep \\\"ASCII text\\\"| tr '\"'\"':'\"'\"' '\"'\"' '\"'\"' \"}' | sh | awk '{print \"echo \\\"\\\" > \" \$1}' | sh" >> $cronFilename
    chmod +x $cronFilename
fi

tagScript success
