#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

# for cwm-based installations, otherwise it's ignored.
if [ ! -f "$CWM_CONFIGFILE" ]; then

    echo "CWM config file not found. Skipping." | log
    tagScript skipped
    exit 99

fi

declare -A timezones
timezones[IL]="Asia/Jerusalem"
timezones[IL-JR]="Asia/Jerusalem"
timezones[IL-TA]="Asia/Jerusalem"
timezones[IL-RH]="Asia/Jerusalem"
timezones[IL-PT]="Asia/Jerusalem"
timezones[EU]="Europe/Amsterdam"
timezones[EU-LO]="Europe/London"
timezones[EU-FR]="Europe/Berlin"
timezones[US-NY2]="America/New_York"
timezones[US-TX]="America/Chicago"
timezones[US-SC]="America/Los_Angeles"
timezones[CA-TR]="America/Toronto"
timezones[AS]="Asia/Hong_Kong"

timedatectl set-timezone $(echo ${timezones[$CWM_ZONE]}) | log

tagScript success

exit 0