#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
autoconfigPath=$rootDir/autoconfig

if [ -f "$rootDir/temp/php-fpm.success" ]; then

    sed -i "s/^serviceRamUsage=[0-9]\+$/serviceRamUsage=50/" $autoconfigPath/php-fpm-autoconfig/php-fpm-autoconfig

fi

if [ -f "$rootDir/temp/mysqld.success" ]; then

    sed -i "s/^serviceRamUsage=[0-9]\+$/serviceRamUsage=50/" $autoconfigPath/mysql-server-autoconfig/mysql-server-autoconfig
    sed -i "s/^serviceCpuUsage=[0-9]\+$/serviceCpuUsage=50/" $autoconfigPath/mysql-server-autoconfig/mysql-server-autoconfig
    
fi

tagScript success

exit 0