#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

echo "Allow binding of MongoDB from all IP Addresses" | log

sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf

echo "Restaring service" | log

systemctl restart mongod.service

tagScript success

exit 0
