#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing update-motd" | log
apt install -y update-motd
waitOrStop 0

echo "cat << EOF " >> /etc/update-motd.d/00-header

cat << EOF >> /etc/update-motd.d/00-header

=== Server Info ==============================================================

  CPU: \`grep -c ^processor /proc/cpuinfo\` Cores of\`cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d':' -f2\`
  RAM: \`free -m | head -n 2 | tail -n 1 | awk {'print \$3'}\`MiB / \`free -m | head -n 2 | tail -n 1 | awk {'print \$2'}\`MiB
  Swap Usage: \`free -m | tail -n 1 | awk {'print \$3'}\`MiB / \`free -m | tail -n 1 | awk {'print \$2'}\`MiB
  Disk Usage of /: \`df -h / | awk '{ a = \$3 } END { print a }'\`iB / \`df -h / | awk '{ a = \$2 } END { print a }'\`iB

  \`uptime -p\` since \`uptime -s\`
  \`ps aux --no-heading | wc -l\` running processes
  System load: \`cat /proc/loadavg | awk '{print \$1 ", " \$2 ", " \$3}'\`

EOF

echo "EOF" >> /etc/update-motd.d/00-header

echo "Removing 10-help-text" | log
rm -f /etc/update-motd.d/10-help-text

echo "Removing 50-motd-news" | log
rm -f /etc/update-motd.d/50-motd-news

echo "Removing 50-landscape-sysinfo" | log
rm -f /etc/update-motd.d/50-landscape-sysinfo

update-motd
waitOrStop 0

tagScript success

exit 0

