#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

apt install -y update-motd | log
waitOrStop 0

rootDir=$(rootDir)

echo "Adding $rootDir/DESCRIPTION.TXT to /etc/update-motd.d/99-DESCRIPTION file" | log

if [ -f "$rootDir/DESCRIPTION.TXT" ];
then

    echo "#!/bin/sh" >> /etc/update-motd.d/99-DESCRIPTION
    echo "=== Installer Description ====================================================" >> /etc/update-motd.d/99-DESCRIPTION
    echo "cat $rootDir/DESCRIPTION.TXT" >> /etc/update-motd.d/99-DESCRIPTION
    echo "==============================================================================" >> /etc/update-motd.d/99-DESCRIPTION
    
    chmod +x /etc/update-motd.d/99-DESCRIPTION

fi

update-motd

exit 0

tagScript success