#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing update-motd" | log
apt install -y update-motd
waitOrStop 0

echo "cat << EOF " >> /etc/update-motd.d/00-header

cat << EOF >> /etc/update-motd.d/00-header

=== Server Info ==============================================================

    OS: `lsb_release -s -d` (`lsb_release -s -c`)

    CPU: `grep -c ^processor /proc/cpuinfo` Cores of `cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d':' -f2`
    CPU Load: `cat /proc/loadavg | awk '{print $1 ", " $2 ", " $3}'`
    RAM:  `free -m | head -n 2 | tail -n 1 | awk {'print $2'}`M		Free RAM:  `free -m | head -n 2 | tail -n 1 | awk {'print $4'}`M
    Swap: `free -m | tail -n 1 | awk {'print $2'}`M		Free Swap: `free -m | tail -n 1 | awk {'print $4'}`M
    Disk: `df -h / | awk '{ a = $2 } END { print a }'`		Free Disk: `df -h / | awk '{ a = $4 } END { print a }'`

==============================================================================

EOF

echo "EOF" >> /etc/update-motd.d/00-header

echo "Removing 10-help-text" | log
rm -f /etc/update-motd.d/10-help-text

echo "Removing 50-motd-news" | log
rm -f /etc/update-motd.d/50-motd-news

update-motd
waitOrStop 0

tagScript success

exit 0

