#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing update-motd" | log
installPackage update-motd
waitOrStop "Failed apt install: update-motd"

echo "Removing 10-help-text" | log
rm -f /etc/update-motd.d/10-help-text

echo "Removing 50-motd-news" | log
rm -f /etc/update-motd.d/50-motd-news

echo "Updating list of packages to upate" | log
echo -e "\n$(/usr/lib/update-notifier/apt-check --human-readable)\n" > /var/lib/update-notifier/updates-available

update-motd

tagScript success

exit 0

