#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

echo "Allow connecting to mySQL with user root from anywhere." | log
mysql --defaults-file=/root/.my.cnf -h localhost <<EOF
USE mysql;
UPDATE USER set Host = '%' where User = 'root';
FLUSH PRIVILEGES;
EOF

echo "Restaring mysql daemon" | log

systemctl restart mysql.service | log

tagScript success

exit 0
