#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

scriptName=$(basename $BASH_SOURCE)
scriptPath=$(dirname $BASH_SOURCE)

echo "Checking existing startup scripts folder" | log

if [ -z "$installerPath" ]; then
	installerPath=/opt/$scriptName
fi

if [ ! -d "$installerPath" ]; then
	mkdir -p $installerPath
fi

cp $scriptPath/extras/$scriptName/* $installerPath/

echo "Setting rc.local to the renamed file if installer is running in a provisioning process." | log

if [ -f "$rcLocalFile.bck" ]; then
    rcLocalFile=/etc/rc.local.bck
else
	rcLocalFile=/etc/rc.local	
fi

if [[ ! -z $(grep $scriptName $rcLocalFile) ]]; then
    echo "$0 is already installed in rc.local" | log
else
    echo "Installing $scriptName in rc.local" | log
    # remove "exit 0" set by default in /etc/rc.local/
    sed -i -e '/exit 0/s/.*//' $rcLocalFile
    echo "bash $installerPath/$scriptName" >> $rcLocalFile
    # return exit 0 to /etc/rc.local
    echo "exit 0" >> $rcLocalFile
fi

echo "Adding descriptions" | log
descriptionAppend "$scriptName script: $installerPath/$scriptName"
descriptionAppend " "

tagScript success

exit 0