#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

echo "Allow binding of mysql from all IP Addresses" | log

sed -i '/^bind-address\t= /{h;s/=.*/= 0.0.0.0/};${x;/^$/{s//bind-address\t= 0.0.0.0/;H};x}' /etc/mysql/mysql.conf.d/mysqld.cnf

echo "Restaring mysql daemon" | log

systemctl restart mysql.service | log
waitOrStop 0 "Restart mysql service failed"

tagScript success

exit 0
