#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success

echo "Generating self-signed certificate" | log
openssl req -x509 -sha256 -newkey rsa:2048 -keyout /etc/ssl/private/server.key -out /etc/ssl/certs/server.crt -days 1024 -nodes -subj '/CN=localhost'
waitOrStop 0 "Certificate creation failed"

echo "Creating an SSL vhost" | log
cat << EOF >> /etc/nginx/sites-available/default-ssl
server {
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;

	ssl_certificate      /etc/ssl/certs/server.crt;
	ssl_certificate_key  /etc/ssl/private/server.key;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		# Default Location
	}
}
EOF

echo "Symlink to sites-enabled" | log 
ln -s /etc/nginx/sites-available/default-ssl /etc/nginx/sites-enabled/default-ssl

echo "Restart NGINX service" | log
systemctl restart nginx.service
waitOrStop 0 "Restart nginx service failed"

descriptionAppend "SSL certificates location: /etc/ssl/"
descriptionAppend " "

tagScript success

exit 0
