#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

### basic check of php-fpm existence ###

service=$(systemctl | grep fpm | awk '{print $1}')

if [[ -z "$service" ]];then
	echo php-fpm is not installed | log
	exit 1
fi

### check existing startup scripts folder ###

MY_PATH="`dirname \"$0\"`"

INSTALLER_PATH="/opt/php-fpm-autoconfig"

if [ ! -d "$INSTALLER_PATH" ]; then
	mkdir -p $INSTALLER_PATH
fi

if [ ! -f "$INSTALLER_PATH/php.ini" ]; then
	cp $MY_PATH/extras/php-fpm-autoconfig/php.ini $INSTALLER_PATH/
fi

if [ ! -f "$INSTALLER_PATH/php-fpm-memadjust" ]; then
	cp $MY_PATH/extras/php-fpm-autoconfig/php-fpm-autoconfig $INSTALLER_PATH/php-fpm-autoconfig
	chmod +x $INSTALLER_PATH/php-fpm-autoconfig
fi

# If installer is running in a provisioning process, set rc.local file to the renamed file.
if [ -f /etc/rc.local.bck ];
then
    RCLOCALFILE=/etc/rc.local.bck
else
    RCLOCALFILE=/etc/rc.local
fi


if [[ -z `cat /etc/rc.local | grep php-fpm-autoconfig` ]];then

    echo "Installing php-fpm-autoconfig in /etc/rc.local" | log

    # remove "exit 0" set by default in /etc/rc.local/
    sed -i -e '/exit 0/s/.*//' $RCLOCALFILE
    echo "$INSTALLER_PATH/php-fpm-autoconfig" >> $RCLOCALFILE

    # return exit 0 to /etc/rc.local
    echo "exit 0" >> $RCLOCALFILE

else

    echo "$0 is already installed in /etc/rc.local" | log

fi

exit 0
