#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

### basic check of php-fpm existence ###

service=$(systemctl | grep fpm | awk '{print $1}')

if [[ -z "$service" ]];then
	echo php-fpm is not installed | log
	exit 1
fi

### check existing startup scripts folder ###

MY_PATH="`dirname \"$0\"`"

INSTALLER_PATH="/opt/cloudwm/installer"

if [ ! -d "$INSTALLER_PATH" ]; then
	mkdir -p $INSTALLER_PATH
fi

if [ ! -f "$INSTALLER_PATH/php.ini" ]; then
	cp $MY_PATH/extras/php-fpm-memadjust-utils/php.ini $INSTALLER_PATH/
fi

if [ ! -f "$INSTALLER_PATH/php-fpm-memadjust" ]; then
	cp $MY_PATH/extras/php-fpm-memadjust-utils/php-fpm-memadjust-util.sh $INSTALLER_PATH/php-fpm-memadjust
	chmod +x $INSTALLER_PATH/php-fpm-memadjust
fi

if [[ `crontab -l | grep -o memadjust` == 'memadjust' ]];then

	echo Cron exists | log
else

	echo "@reboot bash $INSTALLER_PATH/php-fpm-memadjust" >> newcron
	crontab newcron | log
	rm newcron
	bash $INSTALLER_PATH/php-fpm-memadjust | log
fi	

exit 0
