#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist php-fpm.success

rootDir=$(rootDir)
service=$(systemctl | grep fpm | awk '{print $1}')
phpVersion=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")
phpiniPath=/etc/php/$phpVersion/fpm/php.ini

echo "Enabling php to accept short open tags" | log
sed -i -e 's/short_open_tag = Off/short_open_tag = On/' $phpiniPath

echo "Enabling php to display errors in screen" | log
sed -i -e 's/display_errors = Off/display_errors = On/' $phpiniPath

echo "Increasing POST max size to 101M" | log
sed -i -e '/post_max_size/s/8M/101M/' $phpiniPath

echo "Increasing max upload file size to 100M" | log
sed -i -e '/upload_max_filesize/s/2M/100M/' $phpiniPath

if [ -f "$rootDir/temp/nginx.success" ]; then

    echo "Enabling error log file" | log
    sed -i -e 's/;error_log = php_errors.log/error_log = \/var\/log\/nginx\/error.log/' $phpiniPath
    
fi

systemctl restart $service
waitOrStop 0 "Restart service failed"


tagScript success

exit 0