#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

rootDir=$(rootDir)
scriptName=$(basename $BASH_SOURCE)

echo "Checking existing startup scripts folder" | log

if [ -z "$installerPath" ]; then
	installerPath=$rootDir/autoconfig/$scriptName
fi

if [ ! -d "$installerPath" ]; then
	mkdir -p $installerPath
fi

cp $rootDir/tweaks/extras/$scriptName/* $installerPath/

echo "Setting rc.local to the renamed file if installer is running in a provisioning process." | log

rcLocalFile=/etc/rc.local	
if [ -f "$rcLocalFile.bck" ]; then
    rcLocalFile=/etc/rc.local.bck
fi

if [[ ! -z $(grep $scriptName $rcLocalFile) ]]; then
    echo "$0 is already installed in rc.local" | log
else
    echo "Installing $scriptName in rc.local" | log
    # remove exit status set by default or script
    sed -i -e '/exit 0/s/.*//' $rcLocalFile
    sed -i -e '/exit \$exitCode/s/.*//' $rcLocalFile
    # place command script
    echo "bash $installerPath/$scriptName" >> $rcLocalFile
    echo "if [ \$? -ne 0 ]; then exitCode=1; fi;" >> $rcLocalFile
    # reposition exit status after script
    echo "exit \${exitCode:-0}" >> $rcLocalFile
fi

tagScript success

exit 0