#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck
checkTagExist phpmyadmin.success

echo "Changing ownership of phpmyadmin to nginx"
chown -R www-data:www-data /var/www/html/phpmyadmin

echo "Adding to nginx redirect http to https of /phpmyadmin/ " | log

if [ -f "/etc/nginx/sites-available/default" ]; then
    sed -i -e 's/listen 80 default_server;/listen 80 default_server;\n\n        location \/phpmyadmin\/ {\n        try_files $uri $uri\/ =418;\n        return 301 https:\/\/\$host\$request_uri;\n        }\n/' /etc/nginx/sites-available/default
fi

tagScript success

exit 0
