#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

if [ -z "$LANNICIDS" ];
then

REDIS_PASS=`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 12 ; echo ''`
sed -i -e '/^# requirepass foobared/s/.*/requirepass '$REDIS_PASS'/' /etc/redis/redis.conf

descriptionAppend "Password (requirepass): $REDIS_PASS"
descriptionAppend " "
fi

# Restaring redis daemon
systemctl restart redis.service | log
systemctl restart redis-server.service | log

tagScript success

exit 0
