#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

if [ -z "$REDISAUTOCONFIG_DIR" ];
then
    REDISAUTOCONFIG_DIR=/opt/redis-server-autoconfig
fi

if [ ! -d $REDISAUTOCONFIG_DIR ];
then

    mkdir -p $REDISAUTOCONFIG_DIR
fi

rootDir=$(rootDir)

cp -f $rootDir/tweaks/extras/redis-server-autoconfig/* $REDISAUTOCONFIG_DIR

if [[ -z `cat /etc/rc.local | grep redis-server-autoconfig` ]];then

    # remove "exit 0" set by default in /etc/rc.local/
    sed -i -e '/exit 0/s/.*//' /etc/rc.local

    echo "$REDISAUTOCONFIG_DIR/redis-server-autoconfig" >> /etc/rc.local

    # return exit 0 to /etc/rc.local
    echo "exit 0" >> /etc/rc.local

else

    echo "$0 is already installed in /etc/rc.local" | log

fi

tagScript success

exit 0
