#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

if [ -z "$REDISAUTOCONFIG_DIR" ];
then
    REDISAUTOCONFIG_DIR=/opt/redis-server-autoconfig
fi

if [ ! -d $REDISAUTOCONFIG_DIR ];
then

    mkdir -p $REDISAUTOCONFIG_DIR
fi

rootDir=$(rootDir)
echo "Copying redis-server-autoconfig to $REDISAUTOCONFIG_DIR" | log
cp -f $rootDir/tweaks/extras/redis-server-autoconfig/* $REDISAUTOCONFIG_DIR

tagScript success

exit 0
