#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Updating Ubuntu mirrors for Kamatera install" | log
mzone=$(echo ${CWM_ZONE,,} | sed 's/-ny2/-ny/ ; s/as/hk/')
officialDomain="archive.ubuntu.com"
mirrorDomain="ubuntu.mirrors.$mzone-try-kamatera-cloud-now-for-free.kamatera.com"
officialFullDomain="http:\/\/archive.ubuntu.com\/ubuntu"
officialMirrors="mirror:\/\/mirrors.ubuntu.com\/mirrors.txt"

backupFile /etc/apt/sources.list
kamateraMirrors=$(sed -n 's/'"${officialDomain}"'/'"${mirrorDomain}"'/gp' /etc/apt/sources.list)
ubuntuMirrors=$(sed 's/'"${officialFullDomain}"'/'"${officialMirrors}"'/g' /etc/apt/sources.list)
echo -e "#Kamatera Mirrors (1st priority)\n$kamateraMirrors\n\n$ubuntuMirrors" > /etc/apt/sources.list

# prioritize kamatera over official package sources but not over third party sources
# cat << EOF > /etc/apt/preferences.d/kamatera-pin-600

# Package: *
# Pin: origin ${mirrorDomain}
# Pin-Priority: 510

# Package: *
# Pin: origin ${officialDomain}
# Pin-Priority: 500

# EOF

apt update

tagScript success

exit 0