#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Removing floppy module" | log
rmmod floppy |  log
echo "blacklist floppy" | sudo tee /etc/modprobe.d/blacklist-floppy.conf
dpkg-reconfigure initramfs-tools | log
