#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing ufw" | log
installPackage ufw
waitOrStop 0 "Failed apt install: ufw"

ufw --force enable | log
ufw allow 22 | log
ufw status | log

tag ufw.success
tagScript success

exit 0
