#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

echo "Removing /etc/update-motd.d/ unnecessary texts" | log
rm -f /etc/update-motd.d/10-help-text
rm -f /etc/update-motd.d/50-motd-news
cat /dev/null > /var/log/lastlog

tagScript success
