#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist ufw.success

# Check if LAN VLAN exists, if yes, open only LAN VLAN subnets in the firewall for memcached.
# if not, open 11211 to WAN.

if [ ! -z "$CWM_LANNICIDS" ]; then

    for ip in $CWM_LANNICIDS; do

	    ipvar="ip$ip"
    	subnet=`ip -o -f inet addr show | awk '/scope global/ {print $4}' | grep ${!ipvar}`

        ufw allow in to $subnet port 11211

    	unset ipvar
    	unset subnet

    done

else

    ufw allow 11211 | log

fi

ufw status | log

tagScript success
