#!/bin/bash

#
# This script disables Ubuntu Default Installation lxcfs service
#

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

runOnceCheck

echo "Stopping and disabling lxcfs" | log
systemctl stop var-lib-lxcfs.mount | log
systemctl disable lxcfs.service | log

tagScript success