#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist ufw.success

echo "Check if LAN VLAN exists, open only LAN VLAN subnets in the firewall." | log

if [ ! -z "$CWM_LANNICIDS" ]; then

    for nicid in ${CWM_LANNICIDS[@]}; do

        subnet=$(echo "CWM_IP$nicid") 
        ufw allow in to ${!subnet} port 111
        ufw allow in to ${!subnet} port 2049

    done

    unset subnet

else

    lanText="Firewall rules for NFS over WAN are disabled for security reasons. Take care when configuring it manually."
    echo "$lanText" | log
    descriptionAppend "NOTICE: $lanText"
    descriptionAppend " "
    
fi

ufw status | log

tagScript success
