#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Stopping and disabling snapd" | log
systemctl stop snap* | log
systemctl disable snapd | log

apt remove snapd -y | log
rm -Rfv /snap | log 