#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Stopping and disabling iscsid" | log
systemctl stop iscsid | log
systemctl disable iscsid.service | log
apt purge open-iscsi -y | log