#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Stopping and disabling dbus service" | log
systemctl stop dbus.socket | log
systemctl stop dbus.service | log
systemctl disable dbus.socket | log
systemctl disable dbus.service | log

echo "Uninstalling dbus service" | log
apt remove dbus -y | log