#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist ufw.success

ufw allow 21 | log
ufw allow 30000:50000/tcp | log
ufw status | log

tagScript success
