#!/bin/bash

# Load startup scripts if they exist
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

# Check if total swap size is less than 500MB
current_swap_total=$(free -m | awk '/Swap:/ {print $2}')
if [[ $current_swap_total -ge 500 ]]; then
    echo "Sufficient swap space already exists ($current_swap_total MB). No new swap will be created." | log
    exit 0
fi

# Function to create swap
create_swap() {
    swapsize=$1
    swapfile="/swapfile"

    # Creating swap file
    fallocate -l ${swapsize}M ${swapfile} | log
    chmod 600 ${swapfile} | log
    mkswap ${swapfile} | log
    swapon ${swapfile} | log

    # Making the swap file permanent
    echo "${swapfile} none swap sw 0 0" >> /etc/fstab | log

    # Logging swap details
    echo "Swap file created of size ${swapsize}MB" | log
    swapon --show | log
}

# Determine Ubuntu version
ubuntu_version=$(lsb_release -rs)

# Allocate swap based on Ubuntu version
if [[ "$ubuntu_version" == "18.04" || "$ubuntu_version" == "20.04" ]]; then
    create_swap 512
elif [[ "$ubuntu_version" == "22.04" ]]; then
    create_swap 1024
else
    echo "Unsupported Ubuntu version: $ubuntu_version" | log
fi

tagScript success

exit 0
