#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist ufw.success

echo "Check if LAN VLAN exists, open only LAN VLAN subnets in the firewall." | log

if [ ! -z "$LANNICIDS" ]; then

    for ip in $LANNICIDS; do

	    ipvar="ip$ip"
	    subnet=`ip -o -f inet addr show | awk '/scope global/ {print $4}' | grep ${!ipvar}`

        ufw allow in to $subnet port 111
        ufw allow in to $subnet port 2049

	    unset ipvar
	    unset subnet

    done

else

    lanText="Firewall rules for NFS over WAN are disabled for security reasons. Take care when configuring it manually."
    echo "$lanText" | log
    descriptionAppend "NOTICE: $lanText"
    descriptionAppend " "
    
fi

ufw status | log

tagScript success
