#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

# install ufw 
echo "Installing ufw" | log
apt install ufw -y | log
checkPackageInstalled ufw

ufw --force enable | log
ufw allow 22 | log
ufw status | log

tag ufw.success
tagScript success

exit 0
