#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist ufw.success
ports=(4369 5671:5672/tcp 15671 15672 25672 35672:35862/tcp 15674 15675 1883 8883 61613:61614/tcp)
numeric='^[0-9]+$'

# Check if LAN VLAN exists, if yes, open only LAN VLAN subnets in the firewall
if [ ! -z "$CWM_LANNICIDS" ]; then

    for nicid in ${CWM_LANNICIDS[@]}; do

        subnet=$(echo "CWM_IP$nicid") 

        for port in "${ports[@]}"; do

            if ! [[ $port =~ $numeric  ]]; then

                ufw allow in to ${!subnet} from any port ${port/\/*/} proto ${port/*\//}
                continue

            fi

            ufw allow in to ${!subnet} port $port

            #TODO: ufw deny wan

        done

    done

    unset subnet

else

    for port in "${ports[@]}"; do

        ufw allow $port

    done

fi

ufw status | log

tagScript success
