#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist ufw.success

# Check if LAN VLAN exists, if yes, open only LAN VLAN subnets in the firewall for Redis.
# if not, open 6379 to WAN.

if [ ! -z "$CWM_LANNICIDS" ]; then

    for ip in $CWM_LANNICIDS; do

	    ipvar="ip$ip"
	    subnet=`ip -o -f inet addr show | awk '/scope global/ {print $4}' | grep ${!ipvar}`

        ufw allow in to $subnet port 6379

	    unset ipvar
	    unset subnet

    done

else

    ufw allow 6379 | log

fi

ufw status | log

tagScript success
