#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

cp /etc/apt/sources.list /etc/apt/sources.list.bak
mzone=$(echo ${ZONE,,} | sed 's/-ny2/-ny/ ; s/as/hk/')
mirrorDomain="ubuntu.mirrors.$mzone-try-kamatera-cloud-now-for-free.kamatera.com"
sed -i 's/archive.ubuntu.com/'"${mirrorDomain}"'/g' /etc/apt/sources.list

tagScript success

exit 0