#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist ufw.success

# Check if LAN VLAN exists, if yes, open only LAN VLAN subnets in the firewall for memcached.
# if not, open 11211 to WAN.

if [ ! -z "$CWM_LANNICIDS" ]; then

    for nicid in ${CWM_LANNICIDS[@]}; do

        subnet=$(echo "CWM_IP$nicid") 
        ufw allow in to ${!subnet} port 11211

    done

    unset subnet

else

    ufw allow 11211 | log

fi

ufw status | log

tagScript success
