#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist ufw.success

# Check if LAN VLAN exists, if yes, open only LAN VLAN subnets in the firewall for mySQL.
# if not, open 3306 to WAN.

if [ ! -z "$LANNICIDS" ]; then

    for ip in $LANNICIDS;
    do

        ipvar="ip$ip"
        subnet=`ip -o -f inet addr show | awk '/scope global/ {print $4}' | grep ${!ipvar}`

        ufw allow in to $subnet port 4369
        ufw allow in to $subnet port 5671:5672/tcp
        ufw allow in to $subnet port 25672
        ufw allow in to $subnet port 35672:35862/tcp
        ufw allow in to $subnet port 15672
        ufw allow in to $subnet port 61613:61614/tcp
        ufw allow in to $subnet port 1883
        ufw allow in to $subnet port 8883
        ufw allow in to $subnet port 15674
        ufw allow in to $subnet port 15675

        unset ipvar
        unset subnet
    
    done

else

    ufw allow 4369 | log 
    ufw allow 5671:5672/tcp | log
    ufw allow 25672 | log
    ufw allow 35672:35862/tcp | log
    ufw allow 15672 | log
    ufw allow 61613:61614/tcp | log
    ufw allow 1883 | log
    ufw allow 8883 | log
    ufw allow 15674 | log
    ufw allow 15675 | log

fi

ufw status | log

tagScript success
