#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Backuping file /etc/sysctl.conf" | log
backupFile /etc/sysctl.conf | log

echo "Adding to /etc/sysctl.conf tweak values" | log

echo " ">> /etc/sysctl.conf
echo "vm.swappiness = 10" >> /etc/sysctl.conf

sysctl -p