#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Backuping file /etc/sysctl.conf" | log
backupFile /etc/sysctl.conf | log

echo "Adding to /etc/sysctl.conf tweak values" | log

echo " ">> /etc/sysctl.conf
echo "fs.file-max = 10000000" >> /etc/sysctl.conf
echo "fs.nr_open = 10000000" >> /etc/sysctl.conf

echo "net.core.somaxconn = 100000" >> /etc/sysctl.conf
echo "net.core.netdev_max_backlog = 100000" >> /etc/sysctl.conf

echo "net.ipv4.ip_local_port_range = 1024 65535" >> /etc/sysctl.conf

echo "net.ipv4.ip_nonlocal_bind = 1" >> /etc/sysctl.conf
echo "net.ipv4.tcp_fin_timeout = 10" >> /etc/sysctl.conf
echo "net.ipv4.tcp_keepalive_time = 300" >> /etc/sysctl.conf

echo "net.ipv4.tcp_syncookies = 0" >> /etc/sysctl.conf

echo "net.ipv4.tcp_max_orphans = 262144" >> /etc/sysctl.conf
echo "net.ipv4.tcp_max_syn_backlog = 100000" >> /etc/sysctl.conf
echo "net.ipv4.tcp_max_tw_buckets = 262144" >> /etc/sysctl.conf

echo "net.ipv4.tcp_reordering = 3" >> /etc/sysctl.conf

echo "net.ipv4.tcp_mem = 786432 1697152 1945728" >> /etc/sysctl.conf
echo "net.ipv4.tcp_rmem = 4096 87380 16777216" >> /etc/sysctl.conf
echo "net.ipv4.tcp_wmem = 4096 16384 16777216" >> /etc/sysctl.conf

echo "net.ipv4.tcp_syn_retries = 5" >> /etc/sysctl.conf
echo "net.ipv4.tcp_tw_reuse = 1" >> /etc/sysctl.conf

# These values exist only if firewall/iptables conntrack module is loaded.
echo "net.netfilter.nf_conntrack_max = 10485760" >> /etc/sysctl.conf
echo "net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 30" >> /etc/sysctl.conf
echo "net.netfilter.nf_conntrack_tcp_timeout_time_wait = 15" >> /etc/sysctl.conf

sysctl -p