#!/bin/bash
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist ufw.success

ufw allow 21 | log
ufw allow 22 | log
ufw allow 25 | log
ufw allow 53 | log
ufw allow 80 | log
ufw allow 443 | log
ufw allow 110 | log
ufw allow 143 | log
ufw allow 465 | log
ufw allow 587 | log
ufw allow 993 | log
ufw allow 995 | log
ufw allow 8080 | log
ufw allow 8081 | log
ufw allow 10000 | log
ufw allow 40110:40210/tcp | log

ufw status | log

tagScript success
