#
# This is the config file where we define what will be executed in the installer script.
#
# installer will read variables and will execute them one by one.
#

execute+=(include/installInProgressSSH)
execute+=(tweaks/apache-letsencrypt-cert)
execute+=(apps/drupal-latest-offisrc-ubuntu24.04-apache2-mysqlserver-php8.3-fpm)
execute+=(tweaks/mysql-server-autoconfig)
execute+=(tweaks/motd-header-tweak)
execute+=(tweaks/motd-description-append)
execute+=(tweaks/cwm-description-autoconfig)
execute+=(include/installInProgressSSH-remove)