#
# This is the config file where we define what will be executed in the installer script.
#
# installer will read variables and will execute them one by one.
#
. installer-contrib-tweaks-preinstall.conf

execute+=(include/installInProgressSSH)

execute+=(tweaks/cwm-settimezone)
execute+=(tweaks/ubuntu-ufw-enable)
execute+=(tweaks/ubuntu-ufw-allowhttp)
execute+=(tweaks/ubuntu-ufw-allowmysql)

execute+=(tweaks/nginx-letsencrypt-cert)
execute+=(services/mysqlserver-8.0-osrepo)
execute+=(services/ruby-latest-offirepo-ruby-dev)
execute+=(apps/redmine-5.1.3-offisrc-apache-rails-mysql-8.0)

execute+=(tweaks/cwm-description-autoconfig)
execute+=(include/installInProgressSSH-remove)
