#!/bin/bash

installerDir=$(dirname "`readlink -f $0`")

if [ ! -z "$2" ] && [ "$2" == "nospecialkey" ]; then

	export CWM_NO_API_KEY=1

fi

. include/startup.sh

if [ -z "$1" ]; then

    if [ ! -f "./installer.conf" ]; then 

		echo -e "installer.conf file not found.\n Usage: ./installer installer.config.file.conf" | log 1
		exit 1
    fi
	
	. ./installer.conf
    
else

	if [ ! -f "$1" ]; then

		echo "$1 file not found." | log 1
		exit 1

	fi

	. $1

fi

checkRootUser
checkOs

for run in "${execute[@]}"; do

    echo "Executing ${run}" | log
    ${run}
    scriptExitCode=$?

    case "$scriptExitCode" in
		0)
			echo "Done. (0)" | log
			continue
		;;
		1)
			# error log message provided by script
			exit 1
		;;
		98)
			echo "Exit Code 98. Script already executed, can run only once. Continuing. (98)" | log
			continue
		;;
		99)
			echo "Exit Code 99. Continuing. (99)" | log
			continue
		;;
		127)
			echo "Error. ${run} not found. dying. (127)" | log 1
			exit 1
		;;
		*)
			echo "Exit Code not configured. Dying. ($scriptExitCode)" | log 1
			exit 1
		;;
	esac

done
