#
# This is the config file where we define what will be executed in the installer script.
#
# installer will read variables and will execute them one by one.
#
. installer-contrib-tweaks-preinstall.conf

execute+=(include/installInProgressSSH)
execute+=(tweaks/ubuntu-ufw-enable)
execute+=(tweaks/ubuntu-ufw-allowhttp)

. installer-contrib-tweaks-optimize.conf

execute+=(tweaks/nginx-letsencrypt-cert)
execute+=(apps/cpanel_latest_mariadb-10.11_ubuntuserver_24)

execute+=(tweaks/motd-header-tweak)
execute+=(tweaks/motd-description-append)
execute+=(include/installInProgressSSH-remove)
