#!/bin/bash

execute+=(include/installInProgressSSH)

execute+=(tweaks/cwm-settimezone)
execute+=(tweaks/ubuntu-sysctl-swap)
execute+=(include/checkInternetConnectivity)
execute+=(tweaks/ubuntu-disable-openssl-randfile)
execute+=(tweaks/ubuntu-ufw-enable)
execute+=(tweaks/ubuntu-ufw-allowhttp)

execute+=(apps/cloudron-latest-offirepo-24.04)

execute+=(tweaks/motd-header-tweak)
execute+=(tweaks/motd-description-append)
execute+=(tweaks/cwm-description-autoconfig)

execute+=(include/installInProgressSSH-remove)

