#!/bin/bash

# Configure default conf.d location
CNFCONFD="/etc/mysql/mysql.conf.d"


# INNODB Settings 

# Calculate recommended values for InnoDB
innodb_log_file_size=`mysql -e 'select (3838334638 - 3836410803) / 1024 / 1024 as MB_per_min;' | awk 'NR==2{ print int($1*60)"M"}'`
innodb_buffer_pool_size=`cat /proc/meminfo | grep MemTotal | awk {'print int($2/1024/1024*0.8*0.8)'}`

# If not yet configured, cunifgure it
if [ ! -f $CNFCONFD/installer.innodb.cnf ]; then
    echo "[mysqld]" > $CNFCONFD/installer.innodb.cnf
    echo "innodb-flush-method            = O_DIRECT" >> $CNFCONFD/installer.innodb.cnf 
    echo "innodb-log-files-in-group      = 2" >> $CNFCONFD/installer.innodb.cnf
    echo "innodb-log-file-size           = ${innodb_log_file_size}" >> $CNFCONFD/installer.innodb.cnf
    echo "innodb-flush-log-at-trx-commit = 1" >> $CNFCONFD/installer.innodb.cnf
    echo "innodb-file-per-table          = 1" >> $CNFCONFD/installer.innodb.cnf
    echo "innodb-buffer-pool-size        = ${innodb_buffer_pool_size}" >> $CNFCONFD/installer.innodb.cnf
fi

# Fine tuning

max_connections=`nproc | awk '{print $1*100}'`
thread_concurrency=`nproc`

if [ ! -f $CNFCONFD/installer.tuning.cnf ]; then
    echo "[mysqld]" > $CNFCONFD/installer.tuning.cnf
    echo "max_connections              = ${max_connections}" >> $CNFCONFD/installer.tuning.cnf
    echo "thread_concurrency           = ${thread_concurrency}" >> $CNFCONFD/installer.tuning.cnf
fi
