#!/bin/bash

# Configure default conf.d location
CNFCONFD="/etc/mysql/mysql.conf.d"


# INNODB Settings 
totalram=`cat /proc/meminfo | grep MemTotal | awk '{print int($2/1024)}'`

# If not yet configured, configure it
if [ ! -f $CNFCONFD/installer.innodb.cnf ]; then
    # Calculate recommended values for InnoDB
    innodb_log_file_size=`mysql -e 'select (3838334638 - 3836410803) / 1024 / 1024 as MB_per_min;' | awk 'NR==2{ print int($1*60)"M"}'`
    innodb_buffer_pool_size=$(($totalram / 2))

    # Remove current log files
    

    echo "[mysqld]" > $CNFCONFD/installer.innodb.cnf
    echo "innodb-flush-method            = O_DIRECT" >> $CNFCONFD/installer.innodb.cnf 
    echo "innodb-log-files-in-group      = 2" >> $CNFCONFD/installer.innodb.cnf
    echo "innodb-log-file-size           = ${innodb_log_file_size}" >> $CNFCONFD/installer.innodb.cnf
    echo "innodb-flush-log-at-trx-commit = 1" >> $CNFCONFD/installer.innodb.cnf
    echo "innodb-file-per-table          = 1" >> $CNFCONFD/installer.innodb.cnf
    echo "innodb-buffer-pool-size        = ${innodb_buffer_pool_size}M" >> $CNFCONFD/installer.innodb.cnf
fi

# Fine tuning

max_connections=$((($totalram - ($totalram / 2) - 128) / 4))
thread_concurrency=`nproc`

if [ -f $CNFCONFD/installer.tuning.cnf ]; then
    rm -rf $CNFCONFD/installer.tuning.cnf
fi
echo "[mysqld]" > $CNFCONFD/installer.tuning.cnf
echo "max_connections              = ${max_connections}" >> $CNFCONFD/installer.tuning.cnf
echo "innodb_thread_concurrency           = ${thread_concurrency}" >> $CNFCONFD/installer.tuning.cnf
# Default is recommended for those two, should not exceed 200M
# echo "query_cache_size           = 64M" >> $CNFCONFD/installer.tuning.cnf
# echo "key_buffer_size           = 64M" >> $CNFCONFD/installer.tuning.cnf 


# Restart mysql
systemctl restart mysql
