#!/bin/bash

# Configure default conf.d location
CNFCONFD="/etc/mysql/mysql.conf.d"

# Configure the amount of RAM the service will ignore and reserve to OS or other applications (in MB).
reserveRam=300

# Configure the amount of RAM the service will use (in percentage).
serviceRamUsage=100

# Configure the amount of CPUs the service will ignore and reserve to OS or other applications.
reserveCpu=0

# Configure the amount of CPU Cores the service will use (in percentage).
serviceCpuUsage=100

# Get Current Available RAM
totalram=`cat /proc/meminfo | grep MemTotal | awk '{print int($2/1024)}'`

adjustedram=$((($totalram/100) * $serviceRamUsage - $reserveRam))

totalcpu=`nproc`
thread_concurrency=$((($totalcpu * $serviceCpuUsage) / 100 - $reserveCpu))

# If not yet configured, configure it
if [ ! -f $CNFCONFD/installer.innodb.cnf ]; then
    # Calculate recommended values for InnoDB
    # innodb_log_file_size=`mysql --defaults-file=/root/.my.cnf -h localhost -e 'select (3838334638 - 3836410803) / 1024 / 1024 as MB_per_min;' | awk 'NR==2{print int($1*60)"M"}'`
    innodb_buffer_pool_size=$(($adjustedram / 2))
    innodb_buffer_pool_instances=$(($thread_concurrency * 2))

    # Remove current log files
    # rm -rf /var/lib/mysql/ibdata1
    # rm -rf /var/lib/mysql/ib_logfile0
    # rm -rf /var/lib/mysql/logfile1_ib

    # Write calculated values to config
cat << EOF > ${CNFCONFD}/installer.innodb.cnf
[mysqld]
default-storage-engine         = INNODB
innodb-flush-method            = O_DIRECT
innodb-log-files-in-group      = 2
innodb-flush-log-at-trx-commit = 1
innodb-file-per-table          = 1
innodb-buffer-pool-size        = ${innodb_buffer_pool_size}M
innodb_buffer_pool_instances   = ${innodb_buffer_pool_instances}
EOF
#innodb-log-file-size           = ${innodb_log_file_size}

fi

# Fine tuning

max_connections=$((($adjustedram - ($adjustedram / 2) - 128) / 4))
if [ "$max_connections" -lt "20" ]; then
    # For low RAM installations
    max_connections=20
fi

if [ -f $CNFCONFD/installer.tuning.cnf ]; then
    rm -f $CNFCONFD/installer.tuning.cnf
fi
cat << EOF > ${CNFCONFD}/installer.tuning.cnf
[mysqld]
max_connections              = ${max_connections}
innodb_thread_concurrency    = ${thread_concurrency}
EOF
# Default is recommended for those two
#query_cache_size           = 64M
#key_buffer_size           = 64M

# Restart mysql
systemctl restart mysql
