#!/bin/bash

cd /opt/installer 

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Updating description in CWM backend" | log
appendServerDescriptionTXT

tagScript success

exit 0