#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Installing Ansible from APT" | log
installPackage ansible | log
waitOrStop 0 "Failed apt install: Ansible"

# Get ansible Role
ansible-galaxy install severalnines.clustercontrol | log

# install MariaDB:
installPackage install -y mariadb-server | log
installPackage install -y mariadb-client | log

# Create ansible playbook:
cd /root
touch cc.playbook
cat <<EOF > cc.playbook
- hosts: localhost
  roles:
    - { role: severalnines.clustercontrol }
EOF

# Run playbook
ansible-playbook cc.playbook | log


echo "Adding descriptions" | log
descriptionAppend "Default Inventory File: /etc/ansible/hosts"
descriptionAppend " "

tagScript success

exit 0
