#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

appPath=/var/www/html

echo "Install apache from apt" | log
apt install apache2 -y | log
waitOrStop 0

checkPackageInstalled apache2

a2enmod ssl

echo "Changing ownership of $appPath to www-data user" | log
chown -R www-data:www-data $appPath

echo "Enabling apache service" | log
systemctl start apache2.service
systemctl enable apache2.service

echo "Adding descriptions" | log
descriptionAppend "Apache configuration location: /etc/apache2/"
descriptionAppend "Apache root Directory: ${appPath}"
descriptionAppend " "

tag apache2.success
tag httpd.success
tagScript success

exit 0