#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing Apache2..."
installPackage apache2

echo "Installing passenger module for apache2..."
installPackage libapache2-mod-passenger

idxHTMLPath="/etc/apache2/sites-available"
if [ ! -d "$idxHTMLPath" ]; then
	mkdir -p $idxHTMLPath

fi

echo "Writing apache configuration file..."
cat <<_EOF_ > /etc/apache2/sites-available/figletIDX.conf
<VirtualHost *:80>
	ServerName _
	DocumentRoot /etc/apache2/sites-available/

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
<VirtualHost *:443>
    ServerName _
    DocumentRoot /etc/apache2/sites-available/

    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
    SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key

    <Directory /etc/apache2/sites-available/>
        Allow from all
        Options -MultiViews
        Require all granted
    </Directory>
</VirtualHost>
_EOF_

a2enmod ssl
a2dissite 000-default
a2ensite figletIDX
systemctl start apache2

tag apache.success
tag httpd.success
tagScript success

exit 0