#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing Apache2..."
apt update && apt install -y apache2

tag httpd.success
tag apache.success
tagScript success

exit 0
