#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

appPath=/var/www/html

echo "Install apache from apt" | log
installPackage apache2
waitOrStop 0 "Failed apt install: apache2"

echo "Changing ownership of $appPath to www-data user" | log
chown -R www-data:www-data $appPath

echo "Enabling apache service" | log
systemctl start apache2.service
waitOrStop 0 "Starting apache service failed"
systemctl enable apache2.service

echo "Adding descriptions" | log
descriptionAppend "Apache Root Directory: ${appPath}"
descriptionAppend "Apache config files location: /etc/apache2/"
descriptionAppend " "

tag apache2.success
tag httpd.success
tagScript success

exit 0