#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing Apache2..."
installPackage apache2

echo "Installing passenger module for apache2..."
installPackage libapache2-mod-passenger

idxHTMLPath="/var/www/html"
if [ ! -d "$idxHTMLPath" ]; then
	mkdir -p $idxHTMLPath

fi

echo "Writing apache configuration file..."
cat <<_EOF_ > /etc/apache2/sites-available/redmine.conf
<VirtualHost *:80>
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
_EOF_

tag apache.success
tag httpd.success
tagScript success

exit 0