#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Adding Caddy to source list & updating" | log
echo "deb [trusted=yes] https://apt.fury.io/caddy/ /" | tee -a /etc/apt/sources.list.d/caddy-fury.list
apt update | log

echo "Installing Caddy from apt" | log
installPackage caddy
waitOrStop 0 "Failed apt install: caddy"

echo "Adding descriptions" | log
descriptionAppend "Caddy Root Directory: /usr/share/caddy"
descriptionAppend "Caddy config file:/etc/caddyCaddyfile "
descriptionAppend " "

tagScript success
