#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing certbot for apache" | log
add-apt-repository -k hkp://keyserver.ubuntu.com:80 -y ppa:certbot/certbot | log
installPackage python3-certbot-apache
waitOrStop 0 "Failed apt install: python-certbot-apache"

tag certbot-apache2.success
tagScript success

exit 0
