#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success

add-apt-repository ppa:certbot/certbot -y | log
apt install python-certbot-nginx -y | log
waitOrStop 0

checkPackageInstalled python-certbot-nginx

tag certbot-nginx.success
tagScript success

exit 0
