#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist apache2.success

echo "Installing certbot for apache" | log
add-apt-repository ppa:certbot/certbot -y | log
apt install python-certbot-apache -y | log
checkPackageInstalled python-certbot-apache

tag certbot-apache2.success
tagScript success

exit 0
