#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi


checkTagExist litespeed-latest-offirepo.success

echo "Installing certbot for openlitespeed" | log
#Certbot installation
sudo apt-get install certbot -y
waitOrStop 0 "Failed apt install: certbot"

#Certificate request
certbot certonly --non-interactive --agree-tos -m ${ADMINEMAIL} --webroot -w /usr/local/lsws/Example/html/wordpress -d ${CWM_DOMAIN}

###OREN CHANGES###
if [[ $? == 1 ]]
then
export certbot_failed=1
echo "Generating self-signed certificate" | log
#waitOrStop 0 "Failed certbot certificate generation"
mkdir /etc/letsencrypt/live
mkdir /etc/letsencrypt/live/${CWM_DOMAIN}
openssl req -x509 -sha256 -newkey rsa:2048 -keyout /etc/letsencrypt/live/${CWM_DOMAIN}/privkey.pem -out /etc/letsencrypt/live/${CWM_DOMAIN}/cert.pem -days 1024 -nodes -subj '/CN=localhost'
waitOrStop 0 "Certificate creation failed"

# changing configuration - no chain in self signed cert
sed -i "s/CACertPath/#CACertPath/g" /usr/local/lsws/conf/httpd_config.conf
sed -i "s/CACertFile/#CACertFile/g" /usr/local/lsws/conf/httpd_config.conf
else
export certbot_failed=0
fi
###OREN CHANGES###
#waitOrStop 0 "Failed certbot certonly: creating certificate"

#restarting litespeed:
/usr/local/lsws/bin/lswsctrl restart


tag certbot-litespeed.success
tagScript success

exit 0
