#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success

echo "Installing certbot for nginx" | log

###### Oren Testing
#installPackage python3-certbot-nginx
installPackage python3-certbot-apache
###### Oren Testing END

waitOrStop 0 "Failed apt install: python-certbot-nginx"


tag certbot-nginx.success
tagScript success

exit 0
