#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success

echo "Installing certbot for nginx" | log
add-apt-repository -k hkp://keyserver.ubuntu.com:80 -y ppa:certbot/certbot | log
installPackage python-certbot-nginx
waitOrStop 0 "Failed apt install: python-certbot-nginx"

tag certbot-nginx.success
tagScript success

exit 0
