#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rm -rf /usr/src/csf.tgz
wget https://download.configserver.com/csf.tgz -P /usr/src
cd /usr/src && tar -xzf csf.tgz
cd /usr/src/csf/ && sh install.sh

tagScript success
exit 0
