#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installer docker-apt" | log
echo "Downloading docker repository and key" | log
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
waitOrStop 0

add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable edge"
waitOrStop 0

echo "Install docker-ce" | log
apt-get install -y docker-ce
waitOrStop 0

# Enable Service
systemctl enable docker
systemctl enable containerd

tagScript success

exit 0
