#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist mysqld.success

echo "install dovecot from apt" | log

apt install dovecot-imapd dovecot-pop3d dovecot-mysql dovecot-sieve dovecot-lmtpd -y | log
waitOrStop 0

checkPackageInstalled dovecot-imapd 
checkPackageInstalled dovecot-pop3d
checkPackageInstalled dovecot-mysql
checkPackageInstalled dovecot-sieve
checkPackageInstalled dovecot-lmtpd 

tagScript success
exit 0