#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Installing lubuntu Desktop" | log
installPackage lubuntu-desktop
waitOrStop 0 "Failed apt install: lubuntu-desktop"

echo "Add LXDE Session to root user" | log
echo lxsession -s Lubuntu > /root/.xsession

echo "Configuring default theme" | log
cp $rootDir/tweaks/extras/lubuntu-desktop/lubuntu-config.tgz /root/
cd /root/ 
tar -xvzf lubuntu-config.tgz
rm -f /root/lubuntu-config.tgz
chown -R root.root /root
mkdir -p /root/Desktop /root/Documents /root/Downloads /root/Music /root/Pictures /root/Public /root/Templates /root/Videos

tagScript success

exit 0
