#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Install NFS server from apt" | log

installPackage nfs-kernel-server
waitOrStop 0 "Failed apt install: nfs-kernel-server"

echo "Create default Storage directory" | log

mkdir -p /storage
chown nobody:nogroup /storage

echo "Adding default export rule" | log

echo "/storage    *(rw,sync,no_subtree_check)" >> /etc/exports

echo "Restarting services" | log

systemctl enable nfs-kernel-server.service nfs-server.service
systemctl restart nfs-kernel-server.service nfs-server.service

echo "Adding descriptions" | log

descriptionAppend "Network storage location: /storage"
descriptionAppend " "
descriptionAppend "To allow storage access from a client, add it to firewall:"
descriptionAppend "# sudo ufw allow from MY_CLIENT_ADDRESS to any port nfs"
descriptionAppend " "
descriptionAppend "On client, install basic NFS support:"
descriptionAppend "# sudo apt install nfs-common"
descriptionAppend " "
descriptionAppend "On client, connect assigned folder to NFS folder:"
descriptionAppend "# sudo mount ${CWM_SERVERIP}:/storage MY_ASSIGNED_FOLDER"
descriptionAppend " "

tagScript success
exit 0
