#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Install NFS server from apt" | log

apt install nfs-kernel-server -y | log
waitOrStop 0

checkPackageInstalled nfs-kernel-server

echo "Create default Storage directory" | log

mkdir -p /storage
chown nobody:nogroup /storage

echo "Adding default export rule" | log

echo "/storage    *(rw,sync,no_subtree_check)" >> /etc/exports

echo "Restarting services" | log

systemctl enable nfs-kernel-server.service nfs-server.service
systemctl restart nfs-kernel-server.service nfs-server.service

echo "Adding descriptions" | log

descriptionAppend "Network storage location: /storage"
descriptionAppend "To connect with storage, run from client: mount ${SERVERIP}:/storage MY_ASSIGNED_FOLDER"
descriptionAppend " "

tagScript success
exit 0
