#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

# install nginx from apt
apt install nginx -y | log
waitOrStop 0

checkPackageInstalled nginx

echo "Changing ownership of /var/www/html to www-data user" | log
if [ -d "/var/www/html" ]; then
    chown -R www-data:www-data /var/www/html
fi

echo "Adding descriptions" | log
descriptionAppend "NGINX configuration location: /etc/nginx/"
if [ -d "/var/www/html" ]; then
    descriptionAppend "NGINX root Directory: /var/www/html/"
fi
descriptionAppend " "

tag nginx.success
tag httpd.success
tagScript success

exit 0