#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

appPath=/var/www/html
nginxVersion=1.14.\*

echo "install nginx from apt" | log
apt install -y nginx-full=$nginxVersion | log
waitOrStop 0

checkPackageInstalled nginx

echo "Changing ownership of $appPath to www-data user" | log
if [ -d "$appPath" ]; then
    chown -R www-data:www-data $appPath
fi

echo "Adding descriptions" | log
descriptionAppend "NGINX configuration location: /etc/nginx/"

if [ -d "$appPath" ]; then
    descriptionAppend "NGINX root Directory: $appPath/"
fi
descriptionAppend " "

tag nginx.success
tag httpd.success
tagScript success

exit 0