#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

# install nginx from apt
apt install nginx -y | log
waitOrStop 0

checkPackageInstalled nginx

tag nginx.success
tag httpd.success
tagScript success

exit 0