#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

# install nginx from apt
apt install nginx -y | log
waitOrStop 0

checkPackageInstalled nginx

echo "Changing ownership of /var/www/html to www-data user" | log
chown -R www-data:www-data /var/www/html

descriptionAppend "NGINX configuration location: /etc/nginx/"
descriptionAppend "NGINX root Directory: /var/www/html/"
descriptionAppend " "

tag nginx.success
tag httpd.success
tagScript success

exit 0