#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Downloading Node.js repository" | log

curl -sL https://deb.nodesource.com/setup_11.x | sudo bash - | log
waitOrStop 0

echo "Install Node.js" | log

apt-get install -y nodejs build-essential | log
waitOrStop 0

checkPackageInstalled nodejs

tagScript success

exit 0
