#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Downloading Node.js repository" | log

# curl -sL https://deb.nodesource.com/setup_11.x | sudo bash - | log
# waitOrStop 0
curlDownload https://deb.nodesource.com/setup_11.x | log
waitOrStop 0
bash setup_11.x | log
waitOrStop 0

echo "Install Node.js" | log

apt-get install -y nodejs build-essential | log
waitOrStop 0

checkPackageInstalled nodejs

echo "Copying files for testing" | log

cp $rootDir/tweaks/extras/nodejs/hello-world.js ~/
chmod 775 ~/hello-world.js

echo "Adding descriptions" | log

descriptionAppend "To test basic functionality, go to home folder"
descriptionAppend "# cd ~"
descriptionAppend " "
descriptionAppend "Run node with a basic test file which outputs Hello World"
descriptionAppend "# node hello-world.js &"
descriptionAppend " "
descriptionAppend "Access server with curl to see a respone"
descriptionAppend "# curl http://localhost:3000"
descriptionAppend " "

tag nodejs.success
tagScript success

exit 0
