#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing phpMyAdmin" | log
apt install phpmyadmin -y | log
waitOrStop 0

checkPackageInstalled phpmyadmin

tag phpmyadmin.success
tagScript success

exit 0