#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Installing phpMyAdmin" | log
mkdir -p /var/www/html/phpmyadmin
tar -xzvf $rootDir/src/phpMyAdmin-all-languages.tar.gz -C /var/www/html/phpmyadmin/ --strip-components=1
waitOrStop 0



tag phpmyadmin.success
tagScript success

exit 0