#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Installing phpMyAdmin" | log
mkdir -p /var/www/html/phpMyAdmin
cd /var/www/html/phpMyAdmin

tar -xzvf $rootDir/src/phpMyAdmin-all-languages.tar.gz
waitOrStop 0



tag phpmyadmin.success
tagScript success

exit 0