#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Preparing FQDN for installation process" | log
nmcli connection modify eth0 ipv4.dns "8.8.8.8 8.8.4.4"
sed -i "2i${CWM_SERVERIP} ${CWM_DOMAIN}" /etc/hosts
echo ${CWM_SERVERIP} ${CWM_DOMAIN} >> /etc/hosts
hostnamectl set-hostname ${CWM_DOMAIN}

ufw allow 8443
ufw allow 8880

echo "Running Plesk Official Installer" | log
wget http://installer.plesk.com/plesk-installer -O - | sh /dev/stdin --source http://installer.plesk.com/ --target /tmp/plesk-installation --select-product-id plesk --select-release-latest --installation-type "Typical" --notify-email ${ADMINEMAIL}
waitOrStop 0 "File not downloaded from official source"

echo "Adding descriptions" | log
descriptionAppend "Enter Plesk UI to finalize installation: ${CWM_DOMAIN}:8443"
descriptionAppend "Plesk Username: root"
descriptionAppend "Plesk Password: ${ADMINPASSWORD}"
descriptionAppend " "


tagScript success

exit 0
