#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

cat /etc/resolv.conf > /test1.alexey.txt

echo "Preparing FQDN for installation process" | log
sed -i "2i${CWM_SERVERIP} ${CWM_DOMAIN}" /etc/hosts
hostnamectl set-hostname ${CWM_DOMAIN}

cat /etc/resolv.conf > /test2.alexey.txt

ufw allow 8443
ufw allow 8880

cat /etc/resolv.conf > /test3.alexey.txt

echo "Running Plesk Official Installer" | log
wget http://installer.plesk.com/plesk-installer -O - | sh /dev/stdin --source http://installer.plesk.com/ --target /tmp/plesk-installation --select-product-id plesk --select-release-latest --installation-type "Typical" --notify-email ${ADMINEMAIL}
waitOrStop 0 "File not downloaded from official source"

echo "Adding descriptions" | log
descriptionAppend "Enter Plesk UI to finalize installation: ${CWM_DOMAIN}:8443"
descriptionAppend "Plesk Username: root"
descriptionAppend "Plesk Password: ${ADMINPASSWORD}"
descriptionAppend " "


tagScript success

exit 0
