#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Adding hostname to hosts file" | log
echo "127.0.0.1 $(hostname) localhost" > /etc/hosts

echo "Updating and installing PostGreSQL" | log
#Install postgreSQL repository
installPackage wget ca-certificates | log
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - | log
sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' | log

apt-get update
installPackage postgresql postgresql-contrib
waitOrStop 0 "Failed apt install: postgresql"

echo "Changing PostgreSQL listening address" | log
sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/12/main/postgresql.conf

echo "Starting and Enabling PostGreSQL service" | log
systemctl restart postgresql
sleep 2
waitOrStop 0 "Failed to restart postgresql"
systemctl enable postgresql

echo "Adding descriptions" | log
descriptionAppend "To connect to PostGreSQL user: sudo -i -u postgres"
descriptionAppend "To connect to PostGreSQL CLI: psql"
descriptionAppend "PostGreSQL listening port: 5432"
descriptionAppend " "

tagScript success

exit 0
