#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing pure-ftpd" | log
apt install pure-ftpd -y | log
waitOrStop 0
checkPackageInstalled pure-ftpd

# Creating home folder, in case that it wasn't created by web server
mkdir -p  /var/www/html

echo "Creating admin user" | log
(echo "$ADMINPASSWORD" ; echo "$ADMINPASSWORD") | pure-pw useradd admin  -u www-data -d /var/www/html
pure-pw mkdb

echo "Enabling Virtual Users and MinUID for www-data" | log
echo "/usr/sbin/nologin\r" >> /etc/shells
echo "33" > /etc/pure-ftpd/conf/MinUID
ln -s /etc/pure-ftpd/conf/PureDB /etc/pure-ftpd/auth/80puredb

echo "Enabling FTP over Explicit TLS (Port 21)" | log
echo 1 > /etc/pure-ftpd/conf/TLS                
openssl req -x509 -sha256 -newkey rsa:2048 -keyout /etc/ssl/private/pure-ftpd.pem -out /etc/ssl/private/pure-ftpd.pem -days 1024 -nodes -subj '/CN=localhost'
chmod 600 /etc/ssl/private/pure-ftpd.pem

systemctl restart pure-ftpd.service | log

echo "Adding descriptions" | log
descriptionAppend "Pure FTPd config location: /etc/pure-ftpd/conf/"
descriptionAppend " "
descriptionAppend "See all configurations at once:"
descriptionAppend "# head /etc/pure-ftpd/conf/*"
descriptionAppend " "
descriptionAppend "To change a configuration: "
descriptionAppend "# echo {VALUE} > /etc/pure-ftpd/conf/{SETTING}"
descriptionAppend " "
descriptionAppend "Connect from another machine with: "
descriptionAppend "# ftp ${SERVERIP}"
descriptionAppend " "
descriptionAppend "FTP admin user: admin"
descriptionAppend "FTP admin password: ${ADMINPASSWORD}"
descriptionAppend " "
descriptionAppend "Pure FTPd documentation: https://www.pureftpd.org/project/pure-ftpd/doc/"
descriptionAppend " "

tag pure-ftpd.success
tagScript success

exit 0
