#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Add repository" | log

apt-key adv --keyserver "hkps.pool.sks-keyservers.net" --recv-keys "0x6B73A36E6026DFCA"
echo "deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang" | tee /etc/apt/sources.list.d/bintray.rabbitmq.list
echo "deb https://dl.bintray.com/rabbitmq/debian bionic main" >> /etc/apt/sources.list.d/bintray.rabbitmq.list
apt update

echo "Install Erlang & Rabbitmq" | log

# install erlang package
apt install erlang-nox -y
waitOrStop 0
checkPackageInstalled erlang-nox
# install main package
apt install rabbitmq-server -y
waitOrStop 0
checkPackageInstalled rabbitmq-server
# enable web ui plugin
rabbitmq-plugins enable rabbitmq_management

echo "Add admin user" | log

rabbitmqctl add_user admin $ADMINPASSWORD
rabbitmqctl set_user_tags admin administrator
rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"

echo "Open application to remote access" | log

cat << EOF > /etc/rabbitmq/rabbitmq.conf

#listeners.ssl.default = 5671

#ssl_options.cacertfile = /opt/installer/tlsgen/tls-gen/basic/result/ca_certificate.pem
#ssl_options.certfile   = /opt/installer/tlsgen/tls-gen/basic/result/server_certificate.pem
#ssl_options.keyfile    = /opt/installer/tlsgen/tls-gen/basic/result/server_key.pemser
#ssl_options.verify     = verify_peer
#ssl_options.fail_if_no_peer_cert = false

#management.listener.port = 15672
#management.tcp.port       = 15672
listeners.tcp.default = :::5672
#listeners.tcp.1 = :::5672
management.listener.port = 15672
management.listener.ip   = 0.0.0.0
management.listener.ssl  = true
management.listener.ssl_opts.cacertfile = /opt/installer/tlsgen/tls-gen/basic/result/ca_certificate.pem
management.listener.ssl_opts.certfile   = /opt/installer/tlsgen/tls-gen/basic/result/server_certificate.pem
management.listener.ssl_opts.keyfile    = /opt/installer/tlsgen/tls-gen/basic/result/server_key.pem

#management.ssl.port       = 15671
#management.ssl.cacertfile = /opt/installer/tlsgen/tls-gen/basic/result/ca_certificate.pem
#management.ssl.certfile   = /opt/installer/tlsgen/tls-gen/basic/result/server_certificate.pem
#management.ssl.keyfile    = /opt/installer/tlsgen/tls-gen/basic/result/server_key.pem

EOF

echo "Tweaking and optimizing" | log

# port forward to allow access to web ui
#iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 15672

echo "starting Rabbitmq service" | log

systemctl enable rabbitmq-server
systemctl start rabbitmq-server

tagScript success

exit 0
