#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success
rootDir=$(rootDir)

echo "Add repository" | log

apt-key adv --keyserver "hkps.pool.sks-keyservers.net" --recv-keys "0x6B73A36E6026DFCA"
echo "deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang" | tee /etc/apt/sources.list.d/bintray.rabbitmq.list
echo "deb https://dl.bintray.com/rabbitmq/debian bionic main" >> /etc/apt/sources.list.d/bintray.rabbitmq.list
apt update

echo "Install Erlang & Rabbitmq" | log

# install erlang package
apt install erlang-nox -y
waitOrStop 0
checkPackageInstalled erlang-nox
# install main package
apt install rabbitmq-server -y
waitOrStop 0
checkPackageInstalled rabbitmq-server
# enable web ui plugin
rabbitmq-plugins enable rabbitmq_management

echo "Add admin user" | log

rabbitmqctl add_user admin $ADMINPASSWORD
rabbitmqctl set_user_tags admin administrator
rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
rabbitmqctl delete_user guest

echo "Open web UI to remote access" | log
cp -f $rootDir/tweaks/extras/rabbitmq-nginx/rabbitmq-nginx-config /etc/nginx/sites-available/rabbitmq-nginx.conf
ln -s /etc/nginx/sites-available/rabbitmq-nginx.conf /etc/nginx/sites-enabled/
unlink /etc/nginx/sites-enabled/default
unlink /etc/nginx/sites-enabled/default-ssl
systemctl reload nginx

echo "Starting Rabbitmq service" | log

systemctl enable rabbitmq-server
systemctl start rabbitmq-server

echo "Adding descriptions" | log
descriptionAppend "RabbitMQ web UI: https://${SERVERIP}"
descriptionAppend "RabbitMQ config location: /etc/rabbitmq/"

tagScript success

exit 0