#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

# install Redis for local mail delivery
echo "Installing redis" | log

apt install redis -y | log
checkPackageInstalled redis

descriptionAppend "Redis IP Address: ${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "

tag redis.success
tagScript success

exit 0
