#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Adding Redis to apt" | log
add-apt-repository ppa:chris-lea/redis-server
waitOrStop 0
apt update

echo "Installing Redis" | log
apt install redis -y | log
waitOrStop 0

checkPackageInstalled redis

descriptionAppend "Redis IP Address: ${SERVERIP}"
descriptionAppend " "

tag redis.success
tagScript success

exit 0
