#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

appVersion=5:5.0.\*

echo "Adding Redis to apt" | log
add-apt-repository ppa:chris-lea/redis-server -y | log
waitOrStop 0 "Repository not added to source list"
apt update

echo "Installing Redis" | log
apt install -y redis=$appVersion | log
checkPackageInstalled redis

echo "Enabling Redis service" | log
systemctl enable redis-server.service

echo "Adding descriptions" | log
descriptionAppend "Redis IP Address: ${CWM_SERVERIP}"
descriptionAppend " "

tag redis.success
tagScript success

exit 0