#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

appVersion=5:4.0.\*

echo "Installing Redis ${appVersion}" | log
apt install -y redis=$appVersion
checkPackageInstalled redis

echo "Adding descriptions" | log
descriptionAppend "Redis IP Address: ${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "

tag redis.success
tagScript success

exit 0
