#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing Ruby from apt" | log

installPackage ruby-full | log
waitOrStop 0 "Failed to install ruby-full"

tag ruby.success
tagScript success
exit 0