#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing Ruby from apt" | log

apt install -y ruby-full | log
checkPackageInstalled ruby

tag ruby.success
tagScript success
exit 0