#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
mkdir -p $rootDir/temp
rubyVersion=2.6.1
rubyInstallPath=/opt/ruby-$rubyVersion

apt install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev

cd $rootDir/temp
git clone https://github.com/rbenv/ruby-build.git
PREFIX=/usr/local ./ruby-build/install.sh

ruby-build $rubyVersion $rubyInstallPath

echo "Adding Ruby path to global environment and root user" | log
sed -i "s|\"$|:${rubyInstallPath}/bin\"|" /etc/environment
export PATH=`cat /etc/environment | cut -d'"' -f 2`
echo 'export PATH="'$PATH'"' >> ~/.bashrc
source ~/.bashrc

tag ruby.success
tagScript success
exit 0