#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

figletApp=$(which figlet)

echo "Updating 'Installing Ruby...' notice to $appPath/index.html" | log
echo "<html><head><title>Installation Progress</title></head><body><pre align='center'>" > "$appPath/index.html"
$figletApp "Install in Progress" >> "$appPath/index.html"
echo "Please Wait. Installing Ruby..." >> "$appPath/index.html"
echo "</pre></body></html>" >> "$appPath/index.html"

echo "Reloading Apache2..."
systemctl reload apache2

echo "Installing Ruby from apt" | log
installPackage ruby | log
waitOrStop 0 "Failed to install ruby"

installPackage ruby-dev | log
waitOrStop 0 "Failed to install ruby-dev"

installPackage build-essential | log
waitOrStop 0 "Failed to install build-essential"


tag ruby.success
tagScript success
exit 0