#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

# install sendmail for local mail delivery
echo "Installing sendmail" | log
installPackage sendmail
waitOrStop 0 "Failed apt install: sendmail"

tag sendmail.success
tag maild.success
tagScript success

exit 0