#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "install spamassassin from apt" | log

installPackage spamassassin
waitOrStop 0 "Failed apt install: spamassassin"

tagScript success
exit 0