#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
appPath=/etc/tomcat9
assignedPort=9090

echo "Installing main application" | log
packages=(tomcat10 tomcat10-admin tomcat10-docs tomcat10-examples)
installPackage "${packages[@]}"
waitOrStop 0 "Failed apt install: ${packages[@]}"

echo "Enabling service" | log
systemctl enable tomcat10

echo "Removing default configs" | log 
rm -f $appPath/tomcat-users.xml
rm -f $appPath/Catalina/localhost/manager.xml
rm -f $appPath/Catalina/localhost/host-manager.xml

echo "Setting prebuilt configs" | log
cp $rootDir/tweaks/extras/tomcat10-nginx/tomcat-users.xml $appPath/
cp $rootDir/tweaks/extras/tomcat10-nginx/manager.xml $appPath/Catalina/localhost/
cp $rootDir/tweaks/extras/tomcat10-nginx/host-manager.xml $appPath/Catalina/localhost/
sed -i "s/password=\"password\"/password=\"${ADMINPASSWORD}\"/g" $appPath/tomcat-users.xml 
sed -i 's/Connector port="8080"/Connector port="'${assignedPort}'"/g' $appPath/server.xml 

echo "Restarting service" | log
systemctl restart tomcat10
waitOrStop 0 "Restart tomcat service failed"

echo "Setting nginx configuration" | log
nginxConfigPath=/etc/nginx/sites-available
# copy readymade config to nginx sites
cp -f $rootDir/tweaks/extras/tomcat10-nginx/tomcat.conf $nginxConfigPath/
# place chosen port in config
sed -i '/server/s/PORT_PLACEHOLDER/'"${assignedPort}"'/g' $nginxConfigPath/tomcat.conf
ln -s $nginxConfigPath/tomcat.conf /etc/nginx/sites-enabled/
unlink /etc/nginx/sites-enabled/default
unlink /etc/nginx/sites-enabled/default-ssl
service nginx reload
waitOrStop 0 "Reload nginx service failed"

echo "Adding descriptions" | log
descriptionAppend "Apache Tomcat9 Web UI: https://${CWM_DISPLAYED_ADDRESS}"
descriptionAppend "Apache Tomcat9 Username: admin"
descriptionAppend "Apache Tomcat9 Password: ${ADMINPASSWORD}"
descriptionAppend " "
descriptionAppend "Apache Tomcat9 config files location: ${appPath}"
descriptionAppend " "

tagScript success

exit 0
