#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
appPath=/etc/tomcat8

echo "Installing main application" | log
packages=(tomcat8 tomcat8-admin tomcat8-docs tomcat8-examples)
apt install -y "${packages[@]}"
checkPackageInstalled "${packages[@]}"

echo "Enabling service" | log
systemctl enable tomcat8

echo "Removing default configs" | log 
rm -f $appPath/tomcat-users.xml
rm -f $appPath/Catalina/localhost/manager.xml
rm -f $appPath/Catalina/localhost/host-manager.xml

echo "Setting prebuilt configs" | log
cp $rootDir/tweaks/extras/tomcat8/tomcat-users.xml $appPath/
cp $rootDir/tweaks/extras/tomcat8/manager.xml $appPath/Catalina/localhost/
cp $rootDir/tweaks/extras/tomcat8/host-manager.xml $appPath/Catalina/localhost/
sed -i "s/password=\"password\"/password=\"${ADMINPASSWORD}\"/g" $appPath/tomcat-users.xml 
sed -i 's/Connector port="8080"/Connector port="9090"/g' $appPath/server.xml 

echo "Restarting service" | log
systemctl restart tomcat8

echo "Adding descriptions" | log
descriptionAppend "Apache Tomcat8 Web UI: ${CWM_SERVERIP}:9090"
descriptionAppend "Apache Tomcat8 Username: admin"
descriptionAppend "Apache Tomcat8 Password: ${ADMINPASSWORD}"
descriptionAppend " "
descriptionAppend "Apache Tomcat8 config files location: ${appPath}"
descriptionAppend " "

tagScript success

exit 0
