#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
appPath=/etc/tomcat8

echo "Installing main application" | log
apt install -y tomcat8 tomcat8-admin
waitOrStop 0

echo "Enabling service" | log
systemctl enable tomcat8

echo "Removing default configs" | log 
rm -f $appPath/tomcat-users.xml
rm -f $appPath/Catalina/localhost/manager.xml
rm -f $appPath/Catalina/localhost/host-manager.xml

echo "Setting prebuilt configs" | log
cp $rootDir/tweaks/extras/tomcat8/tomcat-users.xml $appPath/
cp $rootDir/tweaks/extras/tomcat8/manager.xml $appPath/Catalina/localhost/
cp $rootDir/tweaks/extras/tomcat8/host-manager.xml $appPath/Catalina/localhost/
sed -i "s/password=\"password\"/password=\"${ADMINPASSWORD}\"/g" $appPath/tomcat-users.xml 
sed -i 's/Connector port="8080"/Connector port="9090"/g' $appPath/server.xml 

echo "Restarting service" | log
systemctl restart tomcat8.service

echo "Adding descriptions" | log
descriptionAppend "Apache Tomcat8 Front Page: ${SERVERIP}:9090"
descriptionAppend "Apache Tomcat8 Manager App: ${SERVERIP}:9090/manager/html"
descriptionAppend "Apache Tomcat8 Host Manager App: ${SERVERIP}:9090/host-manager/html"
descriptionAppend "Apache Tomcat8 Username: admin"
descriptionAppend "Apache Tomcat8 Password: ${ADMINPASSWORD}"
descriptionAppend " "

tagScript success

exit 0
