#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing Ubuntu Desktop" | log
apt install -y libx11-dev libxfixes-dev libssl-dev libpam0g-dev libtool libjpeg-dev flex bison gettext autoconf libxml-parser-perl libfuse-dev xsltproc libxrandr-dev python-libxml2 nasm xserver-xorg-dev fuse pkg-config git intltool xserver-xorg-core ubuntu-desktop
waitOrStop 0

echo "Installing XRDP From Source" | log
cd /tmp && git clone https://github.com/neutrinolabs/xrdp.git
cd /tmp/xrdp && ./bootstrap 
cd /tmp/xrdp && ./configure --enable-fuse --enable-jpeg --enable-rfxcodec
cd /tmp/xrdp/librfxcodec && ./bootstrap
cd /tmp/xrdp/librfxcodec && ./configure
cd /tmp/xrdp && make
cd /tmp/xrdp && make install 

echo "Installing XORG/XRDP From Source" | log
cd /tmp && git clone https://github.com/neutrinolabs/xorgxrdp.git
cd /tmp/xorgxrdp && ./bootstrap 
cd /tmp/xorgxrdp && ./configure 
cd /tmp/xorgxrdp && make 
cd /tmp/xorgxrdp && make install 

echo "Enabling Services" | log
systemctl daemon-reload
systemctl enable xrdp.service
systemctl enable xrdp-sesman.service
systemctl start xrdp

sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
bash -c "cat >/etc/polkit-1/localauthority/50-local.d/45-allow.colord.pkla" <<EOF
[Allow Colord all Users]
Identity=unix-user:*
Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
ResultAny=no
ResultInactive=no
ResultActive=yes
EOF
sed -i.bak "4 a gnome-shell-extension-tool -e ubuntu-appindicators@ubuntu.com\ngnome-shell-extension-tool -e ubuntu-dock@ubuntu.com\n\nif [ -f ~/.xrdp-fix-theme.txt ]; then\necho 'no action required'\nelse\ngsettings set org.gnome.desktop.interface gtk-theme 'Ambiance'\ngsettings set org.gnome.desktop.interface icon-theme 'Humanity'\necho 'check file for xrdp theme fix' >~/.xrdp-fix-theme.txt\nfi\n" /etc/xrdp/startwm.sh

echo "Package cleanup" | log
apt purge -y libx11-dev libxfixes-dev libssl-dev libpam0g-dev libtool libjpeg-dev flex bison gettext autoconf libxml-parser-perl libfuse-dev xsltproc libxrandr-dev python-libxml2 nasm xserver-xorg-dev pkg-config
waitOrStop 0

echo "Adding descriptions" | log
descriptionAppend "Please connect via Microsoft Remote Desktop"
descriptionAppend " "
descriptionAppend "Computer Address: ${SERVERIP}"
descriptionAppend "Ubuntu user: root"
descriptionAppend "Ubuntu password: ${ADMINPASSWORD}"
descriptionAppend " "
tagScript success

exit 0
