#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Running VestaCP Official Installer" | log
curlDownload http://vestacp.com/pub/vst-install.sh
vestaDomain="vesta.${CWM_SERVERIP//./-}.cloud-xip.io"
bash vst-install.sh -n yes -w yes -a no -k yes -v yes -j no -i yes -b yes -q no -x yes -z yes -t yes -c yes -o yes -m yes -g no -y no -p ${ADMINPASSWORD} -e ${ADMINEMAIL} -s ${vestaDomain} | log
waitOrStop 0

echo "Adding descriptions" | log
descriptionAppend "VestaCP Address: https://${vestaDomain}:8083"
descriptionAppend "VestaCP user: admin"
descriptionAppend "VestaCP password: ${ADMINPASSWORD}"
descriptionAppend " "

tagScript success

exit 0
