#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing VirtualBox from apt" | log
installPackage virtualbox virtualbox-ext-pack
waitOrStop 0 "Failed apt install VirtualBox"

tagScript success

exit 0