#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "pre requirements check" | log

checkPackageInstalled php7.2-cli
rootDir=$(rootDir)

echo "install wp cli for wordpress" | log

cd $rootDir/temp
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
waitOrStop 0
chmod +x wp-cli.phar
mv wp-cli.phar /usr/local/bin/wp

echo "check binary existence of wp cli" | log

if [ -f "/usr/local/bin/wp" ]; then
	tag wp-cli.success
	tagScript success
	exit 0
else 
	echo "Failed installing wp-cli"
	exit 1
fi
