#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Installing xRDP service" | log
apt install -y xrdp
checkPackageInstalled xrdp

echo "Restart xRDP service" | log
systemctl restart xrdp

echo "Adding descriptions" | log
descriptionAppend "Please connect via Microsoft Remote Desktop"
descriptionAppend " "
descriptionAppend "Computer Address: ${CWM_SERVERIP}"
descriptionAppend "Ubuntu user: root"
descriptionAppend "Ubuntu password: ${ADMINPASSWORD}"
descriptionAppend " "

tagScript success

exit 0
