#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Installing xRDP service" | log
installPackage xrdp
waitOrStop 0 "Failed apt install: xrdp"
installPackage xserver-xorg-core
waitOrStop 0 "Failed apt install: xserver-xorg-core"
installPackage xserver-xorg-input-all
waitOrStop 0 "Failed apt install: xserver-xorg-input-all"

echo "Installing XFCE4"
installPackage xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils
waitOrStop 0 "Failed apt install: XFCE4"

echo "add user xrdp into ssl-cert group" | log
adduser xrdp ssl-cert

echo "Adding XRDP startup file" | log
rm -rf /etc/xrdp/startwm.sh
cp $rootDir/tweaks/extras/xubuntu-desktop/startwm.sh /etc/xrdp/
chmod +x /etc/xrdp/startwm.sh
rm -rf /etc/pam.d/gdm-password
cp $rootDir/tweaks/extras/xubuntu-desktop/gdm-password /etc/pam.d/

echo "Restart xRDP service" | log
sudo sed -i 's/Exec=exo-open --launch TerminalEmulator/Exec=\/bin\/xfce4-terminal/g' /root/.config/xfce4/panel/launcher-17/*.desktop
systemctl restart xrdp
waitOrStop 0 "Restart xrdp service failed"

echo "Adding descriptions" | log
descriptionAppend "Connect using Microsoft Remote Desktop Client (RDP Client)"
descriptionAppend " "
descriptionAppend "Desktop Address: ${CWM_DISPLAYED_ADDRESS}"
descriptionAppend "Username: root"
descriptionAppend "Password: ${ADMINPASSWORD}"
descriptionAppend " "

tagScript success

exit 0
