#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Installing xRDP service" | log
apt install -y xrdp
checkPackageInstalled xrdp

echo "add user xrdp into ssl-cert group" | log
adduser xrdp ssl-cert

echo "Restart xRDP service" | log
systemctl restart xrdp

echo "Adding descriptions" | log
descriptionAppend "Connect using Microsoft Remote Desktop Client (RDP Client)"
descriptionAppend " "
descriptionAppend "Desktop Address: ${CWM_SERVERIP}"
descriptionAppend "Username: root"
descriptionAppend "Password: ${ADMINPASSWORD}"
descriptionAppend " "

tagScript success

exit 0
