#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Installing xUbuntu Desktop" | log
installPackage xubuntu-desktop
waitOrStop 0 "Failed apt install: xubuntu-desktop"

echo "Add XFCE4 Session to root user" | log
echo /usr/bin/xfce4-session > /root/.xsession

echo "Disable Compositing" | log
mkdir -p /root/.config/xfce4/xfconf/xfce-perchannel-xml
cp $rootDir/tweaks/extras/xubuntu-desktop/xfwm4.xml /root/.config/xfce4/xfconf/xfce-perchannel-xml/

tagScript success

exit 0
