#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success
checkTagExist nginx-enable-ssl.success
checkTagExist jenkins.success

rootDir=$(rootDir)

echo "Setting nginx configuration" | log
cp -f $rootDir/tweaks/extras/jenkins-nginx/jenkins-nginx-config /etc/nginx/sites-available/jenkins.conf
ln -s /etc/nginx/sites-available/jenkins.conf /etc/nginx/sites-enabled/
unlink /etc/nginx/sites-enabled/default
unlink /etc/nginx/sites-enabled/default-ssl
service nginx reload

echo "Tweaking Jenkins configuration" | log
sed -i '/jenkinsUrl/s/>.*</>https://'"${SERVERIP}"'</g' /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml

tagScript success

exit 0