#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Ensuring conntrack modules are enabled" | log 
modprobe ip_conntrack

# disable script after first run
scriptName=$(basename $BASH_SOURCE)
rcLocalFile=/etc/rc.local	
sed -i '/'"${scriptName}"'/s/^/#/g' $rcLocalFile
sed -i '/'"${scriptName}"'/s/^/#/g' $rcLocalFile.bck

tagScript success

exit 0