#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist php.success
checkTagExist mysqld.success

appPath=/var/www/html
rootDir=$(rootDir)

echo "Creating Caddy Database" | log
mysql --defaults-file=/root/.my.cnf -h localhost <<EOF
CREATE DATABASE caddydb CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER 'caddyuser'@'localhost' identified with mysql_native_password by '${ADMINPASSWORD}';
GRANT all privileges on caddydb.* to caddyuser@localhost;
FLUSH PRIVILEGES;
EOF

echo "Removing nginx installed by letsencrypt tweak" | log
systemctl disable --now nginx 2>/dev/null
apt-get purge -y nginx nginx-common 2>&1 | log
apt-get autoremove -y 2>&1 | log

echo "Adding caddy to source list" | log
echo "deb [trusted=yes] https://apt.fury.io/caddy/ /" | tee -a /etc/apt/sources.list.d/caddy-fury.list
apt update | log

echo "Installing Caddy from apt" | log
installPackage caddy | log
waitOrStop 0 "Failed apt install: Caddy"
mkdir -p $appPath
chown -R caddy:caddy /var/log/caddy

LE_DIR="/etc/letsencrypt/live/${CWM_DOMAIN}"
FC_FILE="${LE_DIR}/fullchain.pem"
PK_FILE="${LE_DIR}/privkey.pem"
chmod 755 /etc/letsencrypt/live "${LE_DIR}"
chmod 644 "${FC_FILE}"
chmod 640 "${PK_FILE}"
chown root:caddy "${PK_FILE}"

echo "Creating the Caddy configuration file" | log
cat /dev/null > /etc/caddy/Caddyfile
cat << EOF > /etc/caddy/Caddyfile
${CWM_DOMAIN} {
    root * $appPath
    log {
        output file /var/log/caddy/${CWM_DOMAIN}.access.log {
                roll_size 3MiB
                roll_keep 5
                roll_keep_for 48h
        }
        format console
    }
    encode gzip zstd
    php_fastcgi unix//run/php/php7.4-fpm.sock

    tls ${FC_FILE} ${PK_FILE} {
        protocols tls1.2 tls1.3
    }
}
EOF

echo "Changing PHP permissions" | log
sed -i "s/www-data/caddy/g" /etc/php/7.4/fpm/pool.d/www.conf
sed -i "s/127\.0\.0\.1\:9000/\/run\/php\/php7.4-fpm.sock/g" /etc/php/7.4/fpm/pool.d/www.conf

echo "Setting defualt index file"
cp $rootDir/tweaks/extras/caddy/index.php $appPath
sed -i "s/PASS/${ADMINPASSWORD}/g" $appPath/index.php

echo "Restarting services" | log
systemctl restart php7.4-fpm
waitOrStop 0 "Failed to restart PHP"
systemctl restart caddy
waitOrStop 0 "Failed to restart Caddy"

echo "Adding descriptions" | log
descriptionAppend "Caddy web UI: https://${CWM_DOMAIN}"
descriptionAppend "Caddy configuration file: /etc/caddy/Caddyfile"
descriptionAppend " "

tagScript success

exit 0

