#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Downloading and installing CloudPanel" | log
curl -sS https://installer.cloudpanel.io/ce/v2/install.sh -o install.sh; \
echo "985bed747446eabad433c2e8115e21d6898628fa982c9e55ff6cd0d7c35b501d install.sh" | \
sha256sum -c && sudo DB_ENGINE=MYSQL_8.4 bash install.sh

waitOrStop 0 "Failed to install CloudPanel"

echo "Restarting and enabling  services" | log
systemctl enable nginx
systemctl restart nginx
waitOrStop 0 "Failed to restart nginx"
systemctl enable mysql
systemctl restart mysql
waitOrStop 0 "Failed to restart mysql"

exit 0 

