#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Downloading and installing CloudRon" | log
curlDownload https://cloudron.io/cloudron-setup
chmod +x cloudron-setup
bash cloudron-setup
sleep 5

rm -rf /home/yellowtent/box/dashboard/dist/setupdns.html
rm -rf /home/yellowtent/box/dashboard/dist/js/setupdns.html
cp $rootDir/tweaks/extras/cloudron/setupdns.html /home/yellowtent/box/dashboard/dist/setupdns.html
cp $rootDir/tweaks/extras/cloudron/setupdns.js /home/yellowtent/box/dashboard/dist/js/setupdns.js
sed -i "s/CWMDOMAIN/${CWM_DOMAIN}/g" /home/yellowtent/box/dashboard/dist/setupdns.html
sed -i "s/CWMDOMAIN/${CWM_DOMAIN}/g" /home/yellowtent/box/dashboard/dist/js/setupdns.js

echo "Adding descriptions" | log
descriptionAppend "CloudRon Web UI: https://${CWM_DOMAIN}"
descriptionAppend "SSL will be configured after the first step."

tagScript success

exit 0
