#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

## Ansible Installation ##

#echo "Installing Ansible from APT" | log
#installPackage ansible | log
#waitOrStop 0 "Failed apt install: Ansible"

## Get ansible Role ##
ansible-galaxy install severalnines.clustercontrol | log

## install MariaDB ##
installPackage install -y mariadb-server | log
installPackage install -y mariadb-client | log

## Create ansible playbook ##
cd /root
touch cc.playbook
cat <<EOF > cc.playbook
- hosts: localhost
  roles:
    - { role: severalnines.clustercontrol }
EOF

## Run playbook ##
ansible-playbook cc.playbook | log


echo "Adding descriptions" | log
descriptionAppend "Default Inventory File: /etc/ansible/hosts"
descriptionAppend " "


## Install certbot ##
echo "Installing certbot for apache" | log
installPackage python3-certbot-apache
waitOrStop 0 "Failed apt install: python-certbot-apache"


## applying ssl for cc web app ##
systemctl stop apache2.service
execSpecial 3 '(fail|error)' certbot certonly -n --standalone --preferred-challenges http --agree-tos --email ${ADMINEMAIL} -d ${CWM_DOMAIN} ${CWM_DEBUG:+"--test-cert"}
###OREN CHANGES###
if [[ $? == 1 ]]
then
export certbot_failed=1
echo "Generating self-signed certificate" | log
#waitOrStop 0 "Failed certbot certificate generation"
mkdir /etc/letsencrypt/live
mkdir /etc/letsencrypt/live/${CWM_DOMAIN}
openssl req -x509 -sha256 -newkey rsa:2048 -keyout /etc/letsencrypt/live/${CWM_DOMAIN}/privkey.pem -out /etc/letsencrypt/live/${CWM_DOMAIN}/fullchain.pem -days 1024 -nodes -subj '/CN=localhost'
waitOrStop 0 "Certificate creation failed"

# Sending log to log server - 45-93-93-142.cloud-xip.com
curl -v -X POST -D -H "Content-Type: application/x-www-form-urlencoded" -d "vm_name='$CWM_NAME'&image_name='$CWM_OS'&vm_owner='$ADMINEMAIL'" http://45-93-93-142.cloud-xip.com


else
export certbot_failed=0
fi
###OREN CHANGES###

export CWM_DISPLAYED_ADDRESS="${CWM_DOMAIN}"
systemctl start apache2.service
waitOrStop 0 "Failed to start Apache service"
tag global-domain-set.success

tag ssl-ready.success
tagScript success



## Reconfigure SSL in Vhost ##
sed -i "s|^[ \t]*SSLCertificateFile.*|SSLCertificateFile /etc/letsencrypt/live/$CWM_DOMAIN/fullchain.pem|g" /etc/apache2/sites-available/s9s-ssl.conf
sed -i "s|^[ \t]*SSLCertificateKeyFile.*|SSLCertificateKeyFile /etc/letsencrypt/live/$CWM_DOMAIN/privkey.pem|g" /etc/apache2/sites-available/s9s-ssl.conf
systemctl restart apache2.service

tag apache2.success
tag certbot-apache2.success
tagScript success
exit 0
