#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

## Ansible Installation ##

#echo "Installing Ansible from APT" | log
#installPackage ansible | log
#waitOrStop 0 "Failed apt install: Ansible"

## Get ansible Role ##
ansible-galaxy install severalnines.clustercontrol | log

## install MariaDB ##
installPackage install -y mariadb-server | log
installPackage install -y mariadb-client | log

## Create ansible playbook ##
cd /root
touch cc.playbook
cat <<EOF > cc.playbook
- hosts: localhost
  roles:
    - { role: severalnines.clustercontrol }
EOF

## Run playbook ##
ansible-playbook cc.playbook | log


echo "Adding descriptions" | log
descriptionAppend "Default Inventory File: /etc/ansible/hosts"
descriptionAppend " "


## Install certbot ##
echo "Installing certbot for apache" | log
installPackage python3-certbot-apache
waitOrStop 0 "Failed apt install: python-certbot-apache"


## Reconfigure SSL in Vhost ##
sed -i "s|^[ \t]*SSLCertificateFile.*|SSLCertificateFile /etc/letsencrypt/live/$CWM_DOMAIN/fullchain.pem|g" /etc/apache2/sites-available/s9s-ssl.conf
sed -i "s|^[ \t]*SSLCertificateKeyFile.*|SSLCertificateKeyFile /etc/letsencrypt/live/$CWM_DOMAIN/privkey.pem|g" /etc/apache2/sites-available/s9s-ssl.conf
systemctl restart apache2.service

tag apache2.success
tag certbot-apache2.success
tagScript success
exit 0
