#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Downloading and installing ACME" | log
mkdir -p /root/.acme.sh/
cd /root/.acme.sh/
curlDownload https://raw.githubusercontent.com/acmesh-official/acme.sh/master/acme.sh
waitOrStop 0 "File not downloaded from official source"
chmod +x acme.sh

echo "Downloading and installing CyberPanel & OpenLiteSpeed" | log
mkdir -p /var/www/
cd /var/www/
curl --silent -o cyberpanel.sh "https://cyberpanel.sh/?dl&Ubuntu"
waitOrStop 0 "File not downloaded from official source"
chmod +x cyberpanel.sh
export DEBIAN_FRONTEND=noninteractive
$(bash cyberpanel.sh -v ols -a -p ${ADMINPASSWORD} >/dev/null 2>&1)
waitOrStop 0 "Failed to install CyberPanel"

olspass=$(cat /etc/cyberpanel/webadmin_passwd)

echo "Adding descriptions" | log
descriptionAppend "CyberPanel UI: https://${CWM_DOMAIN}:8090"
descriptionAppend "CyberPanel User: admin"
descriptionAppend "CyberPanel Password: ${ADMINPASSWORD}"
descriptionAppend " "
descriptionAppend "OpenLiteSpeed UI: https://${CWM_DOMAIN}:7080"
descriptionAppend "OpenLiteSpeed User: admin"
descriptionAppend "OpenLiteSpeed Password: ${olspass}"

tagScript success

exit 0
