#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist php.success
checkTagExist nginx.success
checkTagExist nginx-enable-php-ssl.success

appPath=/var/www/html/django
rootDir=$(rootDir)

echo "Creating Django Database" | log
sudo -u postgres psql <<EOF
CREATE DATABASE djangodb WITH OWNER = postgres ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';
CREATE USER djangouser WITH PASSWORD '${ADMINPASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE djangodb TO djangouser;
EOF

# Fix for Ubuntu22.04:
if [[ $(lsb_release -rs) == "22.04" ]]; then
echo "Installing Django and dependencies from apt" | log
installPackage python3-pip python3.10-venv python3-django
waitOrStop 0 "Failed to install python3 dependencies (ubuntu22)"
else
echo "Installing Django and dependencies from apt" | log
installPackage python3-pip python3.8-venv python3-django
waitOrStop 0 "Failed to install python3 dependencies"
fi


echo "Creating Django directory" | log
mkdir -p $appPath
cd $appPath

echo "Creating Python3 enviroment and installing Django from pip" | log
python3 -m venv django_env
source django_env/bin/activate

# Check if Django is installed
if python -c "import django" &> /dev/null; then
    # Get installed version of Django
    django_version=$(python -c "import django; print(django.get_version())")

    # Check if version starts with "2"
    if [[ $django_version == 2.* ]]; then
        echo "Upgrading Django from version $django_version to the latest version." | log
        python3 -m pip install --upgrade django
    else
        echo "Django version $django_version is already up-to-date." | log
    fi
else
    # Install Django
    echo "Django is not installed. Installing the latest version." | log
    python3 -m pip install django
fi

waitOrStop 0 "Failed to install django from pip"

echo "Creating Django project" | log
cd $appPath
django-admin startproject djangoproject .
python3 manage.py migrate
./manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('root', '${ADMINEMAIL}', '${ADMINPASSWORD}')"

sed -i "s/ALLOWED_HOSTS \= \[]/ALLOWED_HOSTS \= \['${CWM_DOMAIN}']/g" $appPath/djangoproject/settings.py

echo "Adding WebUI port to ufw" | log
ufw allow 8000

echo "Creating Django service" | log
cat << EOF > /etc/systemd/system/django.service
[Unit]
Description=Django Web Framework
After=network.target
[Service]
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=django
User=root
ExecStart=python3 $appPath/manage.py runserver ${CWM_DOMAIN}:8000
[Install]
WantedBy=multi-user.target
EOF

echo "Enabling and starting Django service" | log
systemctl daemon-reload
systemctl enable django.service
systemctl start django.service
waitOrStop 0 "Failed to start Django service"

#Alex test start
python3 -m pip install -U Django | log
systemctl restart django.service | log
#Alex test end

echo "Adding descriptions" | log
descriptionAppend "Django Debug mode is on."
descriptionAppend "Make sure to add your website CSS and index files"
descriptionAppend "Django root directory: $appPath"
descriptionAppend "Django settings file: $appPath/djangoproject/settings.py"
descriptionAppend "Django WebUI: http://${CWM_DOMAIN}:8000"
descriptionAppend "Django Admin UI: http://${CWM_DOMAIN}:8000/admin"
descriptionAppend "Django user:root"
descriptionAppend "Django password:${ADMINPASSWORD}"
descriptionAppend " "

tagScript success

exit 0
