#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

appPath=/var/www/html/django

echo "Installing Django and dependencies from apt" | log
installPackage python3-pip python3.8-venv python3-django
waitOrStop 0 "Failed to install python3 dependencies"

echo "Creating Django directory" | log
mkdir -p $appPath
cd $appPath

echo "Creating Python3 enviroment and installing Django from pip" | log
python3 -m venv django_env
source django_env/bin/activate
pip install django
waitOrStop 0 "Failed to install django from pip"

echo "Creating Django project" | log
django-admin startproject djangoproject .
python manage.py migrate

sed -i "s/ALLOWED_HOSTS \= \[]/ALLOWED_HOSTS \= \['${CWM_DOMAIN}']/g" $appPath/djangoproject/settings.py

echo "Adding WebUI port to ufw" | log
ufw allow 8000

echo "Creating Django service" | log
cat << EOF > /etc/systemd/system/django.service
[Unit]
Description=Django Web Framework
After=network.target
[Service]
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=django
User=root
ExecStart=python3 $appPath/manage.py runserver ${CWM_DOMAIN}:8000
[Install]
WantedBy=multi-user.target
EOF

echo "Enabling and starting Django service" | log
systemctl daemon-reload
systemctl enable django.service
systemctl start django.service
waitOrStop 0 "Failed to start Django service"

echo "Adding descriptions" | log
descriptionAppend "run `manage.py createsuperuser` in your project to create a Django user."
descriptionAppend "Django WebUI: http://${CWM_DOMAIN}:8000"
descriptionAppend "Django Admin UI: http://${CWM_DOMAIN}:8000/admin"
descriptionAppend " "

tagScript success

exit 0
