#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success
checkTagExist php.success
checkTagExist nginx-enable-php-ssl.success

rootDir=$(rootDir)

echo "Installing dokuwiki" | log
echo "Downloading dokuwiki from original repo" | log
mkdir -p temp
cd temp
curl -O https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
waitOrStop 0

mkdir -p /var/www/html
mv dokuwiki-stable.tgz /var/www/html 

echo "Extracting dokuwiki to /var/www/html/" | log
tar -xzvf /var/www/html/dokuwiki-stable.tgz -C /var/www/html/ --strip 1
waitOrStop 0
rm -f /var/www/html/dokuwiki-stable.tgz

echo "Setting directory permissions" | log
chown -R www-data.www-data /var/www/html/data/
chown -R www-data.www-data /var/www/html/conf/
chown -R www-data.www-data /var/www/html/inc/
chmod 0700  /var/www/html/data/
chmod 0700  /var/www/html/conf/
chmod 0700  /var/www/html/inc/

echo "Creating nginx configuration" | log
#copy configs to nginx folder
cp $rootDir/tweaks/extras/dokuwiki-nginx/dokuwiki-nginx-config /etc/nginx/sites-available/dokuwiki
# Symlink dokuwiki vhost
ln -s /etc/nginx/sites-available/dokuwiki /etc/nginx/sites-enabled/dokuwiki
# Remove default vhosts
rm -f /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-available/default-ssl
rm -f /etc/nginx/sites-enabled/default
rm -f /etc/nginx/sites-enabled/default-ssl

systemctl restart nginx

# Create Welcome Message
cat << EOF > /var/www/html/data/pages/start.txt
====== You are almost done ======


Please proceed to [[http://${SERVERIP}/install.php|this link]] for additional configuration
EOF
chown www-data:www-data /var/www/html/data/pages/start.txt

tagScript success

exit 0
