#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success
checkTagExist php.success
checkTagExist nginx-enable-php-ssl.success

rootDir=$(rootDir)

echo "Installing dokuwiki" | log
echo "Downloading dokuwiki from original repo" | log
mkdir -p temp
cd temp
curl -O https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
mkdir -p /var/www/html
mv dokuwiki-stable.tgz /var/www/html 
waitOrStop 0

echo "Extracting dokuwiki to /var/www/html/" | log
tar -xzvf /var/www/html/dokuwiki-stable.tgz -C /var/www/html/ --strip 1
waitOrStop 0
rm -f /var/www/html/dokuwiki-stable.tgz
waitOrStop 0

# Set directory permissions
chown -R www-data.www-data /var/www/html/data/
chown -R www-data.www-data /var/www/html/conf/
chown -R www-data.www-data /var/www/html/inc/
chmod 0700  /var/www/html/data/
chmod 0700  /var/www/html/conf/
chmod 0700  /var/www/html/inc/

# Create config file
cp $rootDir/tweaks/extras/dokuwiki-nginx/dokuwiki-nginx-config /etc/nginx/sites-available/dokuwiki

# Create Welcome Message
echo  "====== You are almost done ======" > /var/www/html/data/pages/start.txt
echo  "" >> /var/www/html/data/pages/start.txt
echo  "" >> /var/www/html/data/pages/start.txt
echo  "Please proceed to [[http://${SERVERIP}/install.php|this link]] for additional configuration" >> /var/www/html/data/pages/start.txt

# Symlink dokuwiki vhost
ln -s /etc/nginx/sites-available/dokuwiki /etc/nginx/sites-enabled/dokuwiki
# Remove default vhosts
rm -f /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-available/default-ssl
rm -f /etc/nginx/sites-enabled/default
rm -f /etc/nginx/sites-enabled/default-ssl

systemctl restart nginx

tagScript success

exit 0
