#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success
checkTagExist php.success
checkTagExist nginx-enable-php-ssl.success

versionFilename=dokuwiki-2018-04-22b.tgz
appPath=/var/www/html
rootDir=$(rootDir)
checkTempDir

echo "Installing dokuwiki" | log

echo "Downloading dokuwiki from original repo" | log
cd $rootDir/temp
# curl -O https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
# curlDownload https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz | log
curlDownload https://download.dokuwiki.org/src/dokuwiki/$versionFilename | log
waitOrStop 0

mkdir -p $appPath
mv $versionFilename $appPath

echo "Extracting dokuwiki to ${appPath}/" | log
tar -xzvf $appPath/$versionFilename -C $appPath/ --strip 1
waitOrStop 0
rm -f $appPath/$versionFilename

echo "Setting directory permissions" | log
chown -R www-data.www-data $appPath/data/
chown -R www-data.www-data $appPath/conf/
chown -R www-data.www-data $appPath/inc/
chmod 0700  $appPath/data/
chmod 0700  $appPath/conf/
chmod 0700  $appPath/inc/

echo "Creating nginx configuration" | log
#copy configs to nginx folder
cp $rootDir/tweaks/extras/dokuwiki-nginx/dokuwiki-nginx-config /etc/nginx/sites-available/dokuwiki
# Symlink dokuwiki vhost
ln -s /etc/nginx/sites-available/dokuwiki /etc/nginx/sites-enabled/dokuwiki
# Remove default vhosts
rm -f /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-available/default-ssl
rm -f /etc/nginx/sites-enabled/default
rm -f /etc/nginx/sites-enabled/default-ssl

systemctl restart nginx

# Create Welcome Message
cat << EOF > ${appPath}/data/pages/start.txt
====== You are almost done ======


Please proceed to [[http://${SERVERIP}/install.php|this link]] for additional configuration
EOF
chown www-data:www-data $appPath/data/pages/start.txt

tagScript success

exit 0
