#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success
checkTagExist php.success
checkTagExist nginx-enable-php-ssl.success

versionFilename=2018-04-22b
appPath=/var/www/html
rootDir=$(rootDir)

echo "Installing DokuWiki" | log

echo "Downloading DokuWiki from original repo" | log
cd $rootDir/temp
# curl -O https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
# curlDownload https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz | log
curlDownload https://download.dokuwiki.org/src/dokuwiki/dokuwiki-$versionFilename.tgz
waitOrStop 0

mkdir -p $appPath
mv dokuwiki-$versionFilename.tgz $appPath

echo "Extracting DokuWiki to ${appPath}/" | log
tar -xzvf $appPath/dokuwiki-$versionFilename.tgz -C $appPath/ --strip 1
waitOrStop 0
rm -f $appPath/dokuwiki-$versionFilename.tgz

echo "Setting directory permissions" | log
chown -R www-data.www-data $appPath/data/
chown -R www-data.www-data $appPath/conf/
chown -R www-data.www-data $appPath/inc/
chmod 0700  $appPath/data/
chmod 0700  $appPath/conf/
chmod 0700  $appPath/inc/

echo "Creating nginx configuration" | log
#copy configs to nginx folder
cp $rootDir/tweaks/extras/dokuwiki-nginx/dokuwiki-nginx-config /etc/nginx/sites-available/dokuwiki
# Symlink DokuWiki vhost
ln -s /etc/nginx/sites-available/dokuwiki /etc/nginx/sites-enabled/dokuwiki
# Remove default vhosts
unlink /etc/nginx/sites-enabled/default
unlink /etc/nginx/sites-enabled/default-ssl
systemctl restart nginx

echo "Creating Welcome Message" | log
cat << EOF > ${appPath}/data/pages/start.txt
====== You are almost done ======


Please proceed to [[https://${CWM_SERVERIP}/install.php|this link]] for additional configuration
EOF
chown www-data:www-data $appPath/data/pages/start.txt

echo "Adding descriptions" | log
descriptionAppend "DokuWiki web UI: https://${CWM_SERVERIP}"
descriptionAppend " "

tagScript success

exit 0
