#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist php.success
checkTagExist httpd.success
checkTagExist mysqld.success
checkTagExist nginx-enable-php-ssl.success

rootDir=$(rootDir)

echo "Creating Drupal Database" | log

echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"CREATE DATABASE drupal CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;\"" | sh
echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON drupal.* TO 'drupaluser'@'localhost' IDENTIFIED BY '${ADMINPASSWORD}';\"" | sh
echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"flush privileges;\"" | sh

echo "Installing Composer for machine" | log
apt install composer  -y | log
waitOrStop 0
checkPackageInstalled composer

echo "Downloading latest Drupal" | log
wget  https://www.drupal.org/download-latest/tar.gz -P /var/www/html
waitOrStop 0

echo "Extracting Drupal to /var/www/html/" | log
tar -xzvf /var/www/html/tar.gz -C /var/www/html/ --strip 1
rm -f /var/www/html/tar.gz
waitOrStop 0

echo "Setting misc definitions & permissions for Drupal" | log
cd /var/www/html/sites/default
cp default.settings.php settings.php
cp default.services.yml services.yml
mkdir files/
chmod a+w *

echo "Add temp swap for composer processes" | log
mkdir -p /opt/installer/_swap
cd /opt/installer/_swap
dd if=/dev/zero of=swapfile bs=1M count=1024
mkswap swapfile
swapon swapfile
chmod 600 swapfile
waitOrStop 0

echo "Installing Drush" | log
cd /var/www/html
export COMPOSER_HOME=/root
composer require drush/drush -v | log
# echo y | composer require drush/drush
# composer install --no-dev -o -v | log 
waitOrStop 0

echo "Remove temp swap" | log
cd /opt/installer/_swap
swapoff -v /swapfile
rm /swapfile
waitOrStop 0

echo "Creating Website" | log
cd /var/www/html
echo yes | vendor/bin/drush site-install --db-url=mysql://drupaluser:${ADMINPASSWORD}@localhost/drupal | log
vendor/bin/drush upwd admin ${ADMINPASSWORD} | log


echo "Setting nginx config" | log
#main drupal config
cp $rootDir/tweaks/extras/drupal-nginx/drupal-nginx-config /etc/nginx/sites-available/drupal
# specific configs supplied by nginx for drupal
cp $rootDir/tweaks/extras/drupal-nginx/drupal.conf.sample /etc/nginx/conf.d/drupal.conf.sample
# Symlink drupal vhost
ln -s /etc/nginx/sites-available/drupal /etc/nginx/sites-enabled/drupal
# Remove default vhosts
rm -f /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-available/default-ssl
rm -f /etc/nginx/sites-enabled/default
rm -f /etc/nginx/sites-enabled/default-ssl

systemctl restart nginx

descriptionAppend "Drupal Admin URI: http://${SERVERIP}/admin"
descriptionAppend "Drupal Admin User: admin"
descriptionAppend "Drupal Admin Password: ${ADMINPASSWORD}"

tagScript success

exit 0
