#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist php.success
checkTagExist httpd.success
checkTagExist mysqld.success
checkTagExist nginx-enable-php-ssl.success

rootDir=$(rootDir)

echo "Creating Drupal Database" | log

echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"CREATE DATABASE drupal CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;\"" | sh
echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON drupal.* TO 'drupaluser'@'localhost' IDENTIFIED BY '${ADMINPASSWORD}';\"" | sh
echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"flush privileges;\"" | sh

echo "Installing Composer for machine" | log
apt install composer  -y | log
waitOrStop 0
checkPackageInstalled composer

echo "Downloading latest Drupal" | log
wget  https://www.drupal.org/download-latest/tar.gz -P /var/www/html
waitOrStop 0

echo "Extracting Drupal to /var/www/html/" | log
tar -xzvf /var/www/html/tar.gz -C /var/www/html/ --strip 1
rm -f /var/www/html/tar.gz
waitOrStop 0

echo "Setting misc definitions & permissions for Drupal" | log
cd /var/www/html/sites/default
cp default.settings.php settings.php
cp default.services.yml services.yml
mkdir files/
chmod a+w *
chown -R www-data:www-data files

echo "Create temp swap for composer processes" | log
#increase vm swappiness to allow swap to dominate process
sysctl vm.swappiness=80
# create swap file and moint as partition
swapFilename=$(createSwapFile swapfile 1024 $rootDir/_swap) | log
waitOrStop 0

echo "Installing Drush" | log
cd /var/www/html
export COMPOSER_HOME=/root
composer require drush/drush -v | log
waitOrStop 0

echo "Creating Website" | log
export HOME=/var/www/html
cd /var/www/html
vendor/bin/drush site-install --db-url=mysql://drupaluser:${ADMINPASSWORD}@localhost/drupal | log
vendor/bin/drush upwd admin ${ADMINPASSWORD} | log
rm index.nginx-debian.html
chown -R www-data:www-data .
waitOrStop 0

echo "Setting nginx config" | log
#main drupal config
cp $rootDir/tweaks/extras/drupal-nginx/drupal-nginx-config /etc/nginx/sites-available/drupal
# specific configs supplied by nginx for drupal
cp $rootDir/tweaks/extras/drupal-nginx/drupal-locations.conf /etc/nginx/conf.d/drupal-locations.conf
# Symlink drupal vhost
ln -s /etc/nginx/sites-available/drupal /etc/nginx/sites-enabled/drupal
# Remove default vhosts
rm -f /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-available/default-ssl
rm -f /etc/nginx/sites-enabled/default
rm -f /etc/nginx/sites-enabled/default-ssl

systemctl restart nginx

echo "Remove temp swap" | log
# set vm swappiness to recommended optimal case
sysctl vm.swappiness=10
# mount off and remove swap file 
removeSwapFile $swapFilename
waitOrStop 0

descriptionAppend "Drupal Admin URI: http://${SERVERIP}/admin"
descriptionAppend "Drupal Admin User: admin"
descriptionAppend "Drupal Admin Password: ${ADMINPASSWORD}"

tagScript success

exit 0
