#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing dependencies" | log
installPackage ca-certificates tzdata perl
waitOrStop 0 "Failed to install dependencies"

echo "Downloading GitLab" | log
curlDownload https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
waitOrStop 0 "File not downloaded from official source"
bash script.deb.sh
sleep 20
waitOrStop 0 "Failed to install GitLab"

echo "Installing GitLab from apt" | log
EXTERNAL_URL="https://gitlab.${CWM_DOMAIN}" installPackage gitlab-ce
sleep 20
waitOrStop 0 "Failed to install gitlab-ee"

gitpass=$(cat /etc/gitlab/initial_root_password | grep Password:)

descriptionAppend "GitLab UI: https://${CWM_DOMAIN}"
descriptionAppend " "
descriptionAppend "Default admin account has been configured with following details:"
descriptionAppend "Username: root"
descriptionAppend "${gitpass}"
descriptionAppend "This password will be cleaned up in first reconfigure run after 24 hours."
descriptionAppend " "

tagScript success

exit 0