#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Downloading jenkins repository and key" | log
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
waitOrStop 0

echo "deb https://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list
waitOrStop 0

apt update
bash -c "$(curl -sL https://git.io/vokNn)" 
apt-fast install -y openjdk-8-jre-headless jenkins
waitOrStop 0

unlockkey=`cat /var/lib/jenkins/secrets/initialAdminPassword`

descriptionAppend "Web interface URL: http://${SERVERIP}:8080"
descriptionAppend "Unlock key: $unlockkey"
descriptionAppend " "

tagScript success

exit 0
