#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

appPath=/var/www/html/minecraft

echo "Creating directory and installing dependencies" | log
mkdir -p $appPath
cd $appPath
installPackage openjdk-16-jre-headless | log
waitOrStop 0 "Failed to install openjdk"
installPackage screen | log
waitOrStop 0 "Failed to install screen"

echo "Adding MineCraft server port to FW" | log
ufw allow 25565

echo "Downloading server Jar file" | log
cd $appPath
curlDownload https://launcher.mojang.com/v1/objects/a16d67e5807f57fc4e550299cf20226194497dc2/server.jar
waitOrStop 0 "File not downloaded from official source"
mv server.jar minecraft_server_1.17.1.jar

echo "Starting MineCraft server" | log
cd $appPath
java -Xms1024M -Xmx2G -jar minecraft_server_1.17.1.jar nogui
sed -i "s/eula=false/eula=true/g" $appPath/eula.txt
screen << EOF
java -Xms1024M -Xmx2G -jar minecraft_server_1.17.1.jar nogui
EOF

echo "Adding descriptions" | log
descriptionAppend "MineCraft Server Directory: ${appPath}"
descriptionAppend "MineCraft Server Configuration file: server.properties"
descriptionAppend "To See Session ID run : screen -list"
descriptionAppend "To resume your session: screen -r ID"
descriptionAppend " "

tagScript success

exit 0
