#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
minioConfigFile=/minio/.minio.sys/config/config.json

echo "Adding Minio user" | log
useradd --system minio-user --shell /sbin/nologin

echo "Download Minio Binary" | log
cd $rootDir/temp
curlDownload https://dl.minio.io/server/minio/release/linux-amd64/minio

echo "Install minio binary" | log
mv $rootDir/temp/minio /usr/local/bin
chmod +x /usr/local/bin/minio
chown minio-user:minio-user /usr/local/bin/minio

echo "Creating Configs" | log
mkdir /minio
mkdir /etc/minio
chown minio-user:minio-user /minio
chown minio-user:minio-user /etc/minio
echo "MINIO_VOLUMES=\"/minio/\"" >> /etc/default/minio
ips=$(getServerIPAll)
echo "MINIO_PUBLIC_IPS=${ips// /,}" >> /etc/default/minio
echo "MINIO_OPTS=\"-C /etc/minio --certs-dir /etc/minio/certs --address :443\"" >> /etc/default/minio
setcap 'cap_net_bind_service=+ep' /usr/local/bin/minio

echo "Adding Systemd Service" | log
curlDownload https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service
mv minio.service /etc/systemd/system

echo "Generating self-signed certificate" | log
mkdir -p /etc/minio/certs/
openssl req -x509 -sha256 -newkey rsa:2048 -keyout /etc/minio/certs/private.key -out /etc/minio/certs/public.crt -days 1024 -nodes -subj '/CN=localhost'
chown -R minio-user:minio-user /etc/minio/certs

echo "Starting Minio service" | log
systemctl enable minio.service
systemctl start minio.service
waitOrStop 0 "Minio Service did not start"
sleep 5

echo "Adding descriptions" | log
apt install jq -y
access_key=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16 ; echo '')
secret_key=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16 ; echo '')
sed -i 's/minioadmin/'"${access_key}"'/' $minioConfigFile
sed -i 's/minioadmin/'"${secret_key}"'/' $minioConfigFile
# access_key=$(jq '.credentials._[]|select(.key == "access_key").value' ${minioConfigFile} | tr -d '"')
# secret_key=$(jq '.credentials._[]|select(.key == "secret_key").value' ${minioConfigFile} | tr -d '"')
systemctl restart minio.service
waitOrStop 0 "Minio service did not restart"

descriptionAppend "Minio Web UI: https://${CWM_SERVERIP}"
descriptionAppend "Minio Access key: $access_key"
descriptionAppend "Minio Secret key: $secret_key"
descriptionAppend " "

tagScript success

exit 0
