#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist php.success
checkTagExist nginx.success
checkTagExist mysqld.success
checkTagExist nginx-enable-php-ssl.success

phpVersion=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")
appPath=/var/www/html
rootDir=$(rootDir)
checkTempDir

echo "Downloading NextCloud 15" | log
mkdir -p $appPath
cd $rootDir/temp
# curl -O https://download.nextcloud.com/server/releases/latest-15.tar.bz2 | log
curlDownload https://download.nextcloud.com/server/releases/latest-15.tar.bz2 | log
tar -xjvf latest-15.tar.bz2  -C $appPath/ --strip 1
waitOrStop 0
rm -f latest-15.tar.bz2 
chown -R www-data:www-data $appPath

echo "Preparing database" | log

echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"CREATE DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;\"" | sh
echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"GRANT ALL ON nextcloud.* TO 'nextcloud'@'localhost' IDENTIFIED BY '${ADMINPASSWORD}';\"" | sh
echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"flush privileges;\"" | sh

echo "Installing application" | log

cd $appPath
sudo -u www-data php occ  maintenance:install --database "mysql" --database-name "nextcloud"  --database-user "nextcloud" --database-pass "${ADMINPASSWORD}" --admin-user "admin" --admin-pass "${ADMINPASSWORD}"
sudo -u www-data php occ db:convert-filecache-bigint --no-interaction

echo "Configuring nginx" | log

# Copy Virtual Host
cp $rootDir/tweaks/extras/nextcloud15-nginx/nextcloud15-nginx-config /etc/nginx/sites-available/nextcloud15
# Symlink nextcloud vhost
ln -s /etc/nginx/sites-available/nextcloud15 /etc/nginx/sites-enabled/nextcloud15
# Remove default vhosts
rm -f /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-available/default-ssl
rm -f /etc/nginx/sites-enabled/default
rm -f /etc/nginx/sites-enabled/default-ssl

systemctl restart nginx.service

echo "Tweaking app and runtime settings" | log

# installing image preview functionality
apt install php-imagick -y
waitOrStop 0
checkPackageInstalled php-imagick

# modify php.ini opcache settings
phpIniPath=/etc/php/$phpVersion/fpm/php.ini
sed -i '/opcache.enable=/s/^;//g' $phpIniPath
sed -i '/opcache.memory_consumption=/s/^;//g' $phpIniPath
sed -i '/opcache.interned_strings_buffer=/s/^;//g' $phpIniPath
sed -i '/opcache.max_accelerated_files=/s/^;//g' $phpIniPath
sed -i '/opcache.save_comments=/s/^;//g' $phpIniPath
sed -i "s/;opcache.enable_cli=0/opcache.enable_cli=1/g" $phpIniPath
sed -i "s/;opcache.revalidate_freq=2/opcache.revalidate_freq=1/g" $phpIniPath
# modify www.conf settings
sed -i '/env\[PATH\]/s/^;//g' /etc/php/$phpVersion/fpm/pool.d/www.conf
# Add Server IP to Trusted Servers
sed -i "s/0 => 'localhost',/0 => 'localhost', 1 => '${SERVERIP}',/" $appPath/config/config.php

systemctl restart php$phpVersion-fpm.service

echo "Adding descriptions" | log

descriptionAppend "Nextcloud URL: https://${SERVERIP}/"
descriptionAppend "Nextcloud Username: admin "
descriptionAppend "Nextcloud Password: ${ADMINPASSWORD} "
descriptionAppend " "

tagScript success

exit 0
