#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist php.success
checkTagExist httpd.success

echo "Downloading NextCloud 15" | log
mkdir -p /var/www/html
mkdir -p temp
cd temp
curl -O https://download.nextcloud.com/server/releases/latest-15.tar.bz2| log
tar -xjvf latest-15.tar.bz2  -C /var/www/html/ --strip 1
waitOrStop 0
rm -f platest-15.tar.bz2 
chown -R www-data:www-data /var/www/html

echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"CREATE DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;\"" | sh
echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"GRANT ALL ON nextcloud.* TO 'nextcloud'@'localhost' IDENTIFIED BY '${ADMINPASSWORD}';\"" | sh
echo "mysql --defaults-file=/root/.my.cnf -h localhost -e \"flush privileges;\"" | sh

cd /var/www/html
sudo -u www-data php occ  maintenance:install --database "mysql" --database-name "nextcloud"  --database-user "nextcloud" --database-pass "${ADMINPASSWORD}" --admin-user "admin" --admin-pass "${ADMINPASSWORD}"

# Copy Virtual Host
cp $rootDir/tweaks/extras/nextcloud15-nginx/nextcloud15-nginx-config /etc/nginx/sites-available/nextcloud15
# Symlink nextcloud vhost
ln -s /etc/nginx/sites-available/nextcloud15 /etc/nginx/sites-enabled/nextcloud15
# Remove default vhosts
rm -f /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-available/default-ssl
rm -f /etc/nginx/sites-enabled/default
rm -f /etc/nginx/sites-enabled/default-ssl

systemctl restart nginx.service

# Add Server IP to Trusted Servers
sed -i "s/0 => 'localhost',/0 => 'localhost', 1 => '${SERVERIP}',/" /var/www/html/config/config.php

descriptionAppend "Nextcloud URL: https://${SERVERIP}/"
descriptionAppend " "
descriptionAppend "Nextcloud Username: admin "
descriptionAppend "Nextcloud Password: ${ADMINPASSWORD} "

tagScript success

exit 0
