#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing dependencies" | log
packages=(python3-pip build-essential wget python3-dev python3-venv \
          python3-wheel libfreetype6-dev libxml2-dev libzip-dev libldap2-dev libsasl2-dev \
          python3-setuptools node-less libjpeg-dev zlib1g-dev libpq-dev \
          libxslt1-dev libldap2-dev libtiff5-dev libjpeg8-dev libopenjp2-7-dev \
          liblcms2-dev libwebp-dev libharfbuzz-dev libfribidi-dev libxcb1-dev)
installPackage "${packages[@]}" | log
waitOrStop 0 "Failed to install dependencies"

echo "Create app user" | log
useradd -m -d /opt/odoo14 -U -r -s /bin/bash odoo14

echo "Installing postgresql" | log
installPackage postgresql | log
waitOrStop 0 "Failed to install postgresql"

echo "Downloading and installing wkhtmltox"
curlDownload https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
waitOrStop 0 "File not downloaded from official source"

su odoo14 << EOF
git clone https://www.github.com/odoo/odoo --depth 1 --branch 14.0 /opt/odoo14/odoo
cd /opt/odoo14
python3 -m venv odoo-venv
source odoo-venv/bin/activate
pip3 install wheel
pip3 install -r odoo/requirements.txt
deactivate
mkdir -p /opt/odoo14/odoo-custom-addons
EOF

echo "Creating Odoo service"
cat << EOF > /etc/odoo14.conf
[options]
; This is the password that allows database operations:
admin_passwd = $ADMINPASSWORD
db_host = False
db_port = False
db_user = odoo14
db_password = False
addons_path = /opt/odoo14/odoo/addons,/opt/odoo14/odoo-custom-addons

EOF

cat << EOF > /etc/systemd/system/odoo14.service
[Unit]
Description=Odoo14
Requires=postgresql.service
After=network.target postgresql.service

[Service]
Type=simple
SyslogIdentifier=odoo14
PermissionsStartOnly=true
User=odoo14
Group=odoo14
ExecStart=/opt/odoo14/odoo-venv/bin/python3 /opt/odoo14/odoo/odoo-bin -c /etc/odoo14.conf
StandardOutput=journal+console

[Install]
WantedBy=multi-user.target

EOF

ufw allow 8069

echo "Creating Odoo14 user in postgres" | log
su - postgres psql -c "createuser -s odoo14"

systemctl daemon-reload
waitOrStop 0 "Reloading daemon failed"
systemctl enable odoo14
sleep 1
systemctl start odoo14
sleep 2
waitOrStop 0 "Start Odoo14 service failed"

echo "Adding descriptions" | log
descriptionAppend "Odoo configuration file: /etc/odoo14.conf"
descriptionAppend "Odoo web UI: http://${CWM_DISPLAYED_ADDRESS}:8069"
descriptionAppend " "

tagScript success

exit 0

