#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Downloading OpenProject key and adding to source list" | log
curlDownload https://dl.packager.io/srv/opf/openproject/key
waitOrStop "Failed to download PGP key"
apt-key add key
echo "deb https://dl.packager.io/srv/deb/opf/openproject/stable/11/ubuntu 20.04 main" | tee /etc/apt/sources.list.d/openproject.list

echo "Updating and installing OpenProject from apt" | log
apt-get update
installPackage openproject
waitOrStop "Failed to install OpenProject"

echo "Adding descriptions" | log
descriptionAppend " "
descriptionAppend " "

tagScript success

exit 0

