#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

mv /etc/letsencrypt/live/${CWM_DOMAIN}/fullchain.pem /etc/letsencrypt/live/${CWM_DOMAIN}/cert.pem
sed -i "s|SSLCACertificateFile|#SSLCACertificateFile|" /etc/openproject/addons/apache2/includes/vhost/ssl_ca.conf

# Install dependencies for repository access
echo "Installing dependencies for repository access" | log
installPackage apt-transport-https ca-certificates wget gpg
waitOrStop 0 "Failed to install repository dependencies"

# Add OpenProject GPG key securely
echo "Downloading OpenProject key and adding to trusted GPG keys" | log
curlDownload https://dl.packager.io/srv/opf/openproject/key
waitOrStop 0 "Failed to download PGP key"
gpg --dearmor < key > /etc/apt/trusted.gpg.d/openproject.gpg
rm key

# Add OpenProject repository for Ubuntu 22.04 
echo "Adding OpenProject repository" | log
curlDownload https://dl.packager.io/srv/opf/openproject/stable/16/installer/ubuntu/22.04.repo
waitOrStop 0 "Failed to download OpenProject repository file"
mv 22.04.repo /etc/apt/sources.list.d/openproject.list

# Update package index and install OpenProject
echo "Updating and installing OpenProject" | log
apt-get update
installPackage openproject
waitOrStop 0 "Failed to install OpenProject"

# Configure OpenProject
echo "Setting installation variables and configuring OpenProject" | log
cp $rootDir/tweaks/extras/openproject/installer.dat /etc/openproject/
sed -i "s/ServerDomain/${CWM_DOMAIN}/g" /etc/openproject/installer.dat
sed -i "s/USEREMAIL/${ADMINEMAIL}/g" /etc/openproject/installer.dat
export DEBIAN_FRONTEND=noninteractive
openproject configure
waitOrStop 0 "Failed to configure OpenProject"

# Add descriptions
echo "Adding descriptions" | log
descriptionAppend "OpenProject Web UI: https://${CWM_DOMAIN}"
descriptionAppend "OpenProject default user: admin"
descriptionAppend "OpenProject default password: admin"

tagScript success
