#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist php.success
checkTagExist httpd.success

rootDir=$(rootDir)
myadminPath=/var/www/html/phpmyadmin

echo "Installing phpMyAdmin" | log
mkdir -p $myadminPath
wget https://files.phpmyadmin.net/phpMyAdmin/5.2.0/phpMyAdmin-5.2.0-all-languages.tar.gz
tar -xzvf $rootDir/src/phpMyAdmin-5.2.0-all-languages.tar.gz -C $myadminPath/ --strip-components=1
waitOrStop 0 "Failed to extract application archive"

echo "Setting default config file" | log
cd $myadminPath
mv config.sample.inc.php config.inc.php

echo "Making sure tmp folder exists" | log
if [ ! -d "$myadminPath/tmp" ]; then
    echo "tmp directory doesn't exist, creating it." | log
    mkdir -p $myadminPath/tmp/
fi
chown -R www-data:www-data $myadminPath/tmp/

echo "Generating blowfish_secret string and replacing it in config.inc.php" | log
blowfish_secret=`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32 ; echo ''`
sed -i "/$cfg\['blowfish_secret.*/c\$cfg['blowfish_secret'] = '"$blowfish_secret"';" config.inc.php

descriptionAppend "phpMyAdmin Web UI: https://${CWM_DISPLAYED_ADDRESS}/phpmyadmin"
descriptionAppend " "

tag phpmyadmin.success
tagScript success

exit 0
