#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success

rootDir=$(rootDir)

echo "Installing snap and then rocket.chat" | log
installPackage snapd
waitOrStop 0 "Failed apt install: snapd"
snap install rocketchat-server 
waitOrStop 0 "Failed to install snap application"

echo "Adding Loading in Progress screen" | log
nginxErrorPage=/usr/share/nginx/html/customerror_50x.html
useFiglet
printf "<pre align=center>\n" > $nginxErrorPage
bannerFiglet "Loading in Progress\n Please Wait.\n" >> $nginxErrorPage
printf "Application and services loading is in progress, process will take a couple of minutes to complete \n\nThank you for your patience.\n\nRefresh page within a couple of minutes for updated status." >> $nginxErrorPage

echo "Configuring nginx" | log
cp -f $rootDir/tweaks/extras/rocketchat-nginx/rocketchat.conf /etc/nginx/sites-available/
ln -s /etc/nginx/sites-available/rocketchat.conf /etc/nginx/sites-enabled/
unlink /etc/nginx/sites-enabled/default
unlink /etc/nginx/sites-enabled/default-ssl
systemctl reload nginx
waitOrStop 0 "Reload nginx service failed"

echo "Adding descriptions" | log
descriptionAppend "Rocket.chat Web UI: https://${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "
descriptionAppend "Rocket.chat application directories:"
descriptionAppend "/snap/rocketchat-server/"
descriptionAppend "/var/snap/rocketchat-server"
descriptionAppend " "
descriptionAppend "Rocket.chat mongoDB management:"
descriptionAppend "# rocketchat-server.mongo parties"
descriptionAppend " "
descriptionAppend "Rocket.chat service logs:"
descriptionAppend "# journalctl -f -u snap.rocketchat-server.rocketchat-server"
descriptionAppend "# journalctl -f -u snap.rocketchat-server.rocketchat-mongo"
descriptionAppend "# journalctl -f -u snap.rocketchat-server.rocketchat-caddy"
descriptionAppend " "
descriptionAppend "Rocket.chat service control: (status/start/stop/restart)"
descriptionAppend "# service snap.rocketchat-server.rocketchat-[SERVICE] [COMMAND]"
descriptionAppend " "
descriptionAppend "For example:"
descriptionAppend "# service snap.rocketchat-server.rocketchat-server restart"
descriptionAppend "# service snap.rocketchat-server.rocketchat-mongo status"
descriptionAppend "# service snap.rocketchat-server.rocketchat-caddy stop"
descriptionAppend " "
descriptionAppend "For further information:"
descriptionAppend "https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/"
descriptionAppend " "

tagScript success

exit 0