#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
app_path=/opt/rocket

echo "Installing Packages" | log
packages=(nginx gnupg2 git unzip build-essential curl software-properties-common graphicsmagick)
installPackage "${packages[@]}" | log
waitOrStop 0 "Failed apt install: ${packages[@]}"

echo "Downloading Node.js repository" | log
curlDownload https://deb.nodesource.com/setup_12.x
waitOrStop 0 "File not downloaded from official source"
bash setup_12.x | log
waitOrStop 0 "Failed to install application"

echo "Installing Node.js" | log
apt-get install nodejs -y | log

echo "Installing and configuring MongoDB"
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
add-apt-repository 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse'
installPackage mongodb-org
waitOrStop 0 "Failed apt install MongoDB"
systemctl start mongod
systemctl enable mongod
sed -i "s/#replication/replication/g" /etc/mongod.conf
sed -i "/replication:/ a \    replSetName: "replica01"" /etc/mongod.conf
systemctl restart mongod

mongo << EOF
rs.initiate()
EOF

echo "Setting permissions for RocketChat"
useradd -m -U -r -d /opt/rocket rocket --shell /bin/bash
usermod -a -G rocket www-data
chmod 750 /opt/rocket

echo "Downloading latest RocketChat"
cd ${app_path}
curlDownload https://releases.rocket.chat/latest/download $app_path/rocket.chat.tgz
waitOrStop 0 "File not downloaded from official source"

su rocket << EOF
tar -xvzf rocket.chat.tgz
mv bundle Rocket.Chat
cd Rocket.Chat/programs/server
npm install
EOF

echo "Installing service" | log
cat << EOF > /etc/systemd/system/rocketchat.service

[Unit]
Description=Rocket.Chat server
After=network.target nss-lookup.target mongod.target

[Service]
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocket
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://${CWM_DISPLAYED_ADDRESS} PORT=3000
ExecStart=/usr/bin/node /opt/rocket/Rocket.Chat/main.js

[Install]
WantedBy=multi-user.target

EOF

systemctl daemon-reload
waitOrStop 0 "Reload systemctl failed"
systemctl start rocketchat
waitOrStop 0 "Start rocketchat service failed"
systemctl enable rocketchat

ln -s /etc/nginx/sites-available/rocketchat.conf /etc/nginx/sites-enabled/
systemctl restart nginx
waitOrStop 0 "Restarting NGINX failed"

descriptionAppend "Rocket.chat application directory: ${app_path}/Rocket.Chat/"
descriptionAppend "Rocket.chat web UI: http://${CWM_DISPLAYED_ADDRESS}"
descriptionAppend " "

tagScript success

exit 0
