#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

serviceFile="/lib/systemd/system/teamspeak.service"
appDir="/home/teamspeak"

echo "Installing bzip2" | log
installPackage bzip2
waitOrStop 0 "Failed to install package"

echo "Creating TeamSpeak User" | log 
adduser --disabled-login --gecos "" teamspeak
cd /home/teamspeak

echo "Downloading TeamSpeak from official source" | log 
curlDownload https://files.teamspeak-services.com/releases/server/3.13.7/teamspeak3-server_linux_amd64-3.13.7.tar.bz2
tar xvf teamspeak3-server_linux_amd64-3.13.7.tar.bz2
rm -f teamspeak3-server_linux_amd64-3.13.7.tar.bz2
cd teamspeak3-server_linux_amd64 && mv * /home/teamspeak && cd ..
touch .ts3server_license_accepted
echo "license_accepted=1" > .ts3server_license_accepted

echo "Creating TeamSpeak Service" | log
tee "$serviceFile" <<EOF
[Unit]
Description=TeamSpeak 3 Server
After=network.target

[Service]
WorkingDirectory=/home/teamspeak/
User=teamspeak
Group=teamspeak
Type=forking
ExecStart=/home/teamspeak/ts3server_startscript.sh start inifile=ts3server.ini
ExecStop=/home/teamspeak/ts3server_startscript.sh stop
PIDFile=/home/teamspeak/ts3server.pid
RestartSec=15
Restart=always

[Install]
WantedBy=multi-user.target
EOF

echo "Allowing ports" | log 
ufw allow 9987
ufw allow 10011
ufw allow 30033

systemctl enable teamspeak
waitOrStop 0 "Failed to enable teamspeak service"
systemctl start teamspeak
waitOrStop 0 "Failed to start teamspeak"
sleep 5

echo "Extracting token" | log
TS3_TOKEN=$(grep "token=" /opt/teamspeak/teamspeak3-server_linux_amd64/logs/ts3server_*.log | awk -F'=' '{print $2}')
my_ip=$(curl -s ifconfig.me)

echo "Adding descriptions" | log
descriptionAppend "Use your machine IP to connect via TeamSpeak client: $my_ip"
descriptionAppend "Teamspeak password: $ADMINPASSWORD"
descriptionAppend "This is the token you need to confirm your connection: $TS3_TOKEN"
descriptionAppend "TeamSpeak config files located here: $appDir"
descriptionAppend "You can allow IPs in this config file: query_ip_allowlist.txt, one IP per line"

tagScript success

exit 0

