#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

appDir="/opt/teamspeak"
installPackage bzip2

echo "Downloading TeamSpeak from official source"
curlDownload https://files.teamspeak-services.com/releases/server/3.13.7/teamspeak3-server_linux_amd64-3.13.7.tar.bz2
mkdir -p $appDir
mv teamspeak3-server_linux_amd64-3.13.7.tar.bz2 $appDir
cd $appDir
tar -xjvf teamspeak3-server_linux_amd64-3.13.7.tar.bz2
rm -f teamspeak3-server_linux_amd64-3.13.7.tar.bz2
useradd -m -d $appDir -s /bin/bash -c "TeamSpeak Server User" teamspeak
chown -R teamspeak:teamspeak $appDir
cd teamspeak3-server_linux_amd64
touch $appDir/teamspeak3-server_linux_amd64/.ts3server_license_accepted
echo "license_accepted=1" > .ts3server_license_accepted
echo "Starting teamspeak" | log

cat <<EOF | tee /etc/systemd/system/teamspeak.service
[Unit]
Description=Teamspeak Service
Wants=network.target

[Service]
Environment=TS3SERVER_LICENSE=accept
WorkingDirectory=${appDir}/teamspeak3-server_linux_amd64
User=root
ExecStart=${appDir}/teamspeak3-server_linux_amd64/ts3server_minimal_runscript.sh
ExecStop=${appDir}/teamspeak3-server_linux_amd64/ts3server_startscript.sh stop
ExecReload=${appDir}/teamspeak3-server_linux_amd64/ts3server_startscript.sh restart
Restart=always
RestartSec=15

[Install]
WantedBy=multi-user.target
EOF

echo "Reloading daemon"
systemctl daemon-reload
waitOrStop 0 "Failed to reload daemon"
systemctl enable --now teamspeak
waitOrStop 0 "Failed to enable teamspeak service"
systemctl stop teamspeak
waitOrStop 0 "Failed to stop teamspeak"
./ts3server_startscript.sh start serveradmin_password=$ADMINPASSWORD
waitOrStop 0 "Failed to pass serveradmin password"
systemctl restart teamspeak
waitOrStop 0 "Failed to start teamspeak"
echo "Extracting token" | log
TS3_TOKEN=$(grep "token=" /opt/teamspeak/teamspeak3-server_linux_amd64/logs/ts3server_*.log | awk -F'=' '{print $2}')
my_ip=${curl -s ifconfig.me}
echo "Adding descriptions" | log

descriptionAppend "Use your machine IP to connect via TeamSpeak client: $myip"
descriptionAppend "Teamspeak password: $ADMINPASSWORD"
descriptionAppend "This is the token you need to confirm your connection: $TS3_TOKEN"
descriptionAppend "TeamSpeak config files located here: $appDir"
descriptionAppend "You can allow IPs in this config file: query_ip_allowlist.txt, one IP per line"

tagScript success

exit 0

