#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)

echo "Updating NPM" | log
npm install npm -g

echo "Cloning UpTimeKuma Git Repository" | log
mkdir -p /var/www/
cd /var/www/
git clone https://github.com/louislam/uptime-kuma.git

echo "Installing UpTimeKuma" | log
cd /var/www/uptime-kuma/
npm run setup
sleep 3

echo "Adding FW rule" | log
ufw allow 3001

echo "Installing PM2 from NPM" | log
npm install pm2 -g

echo "Launching Application with PM2" | log
pm2 start /var/www/uptime-kuma/server/server.js --name uptime-kuma -- --port=3001 --hostname=${CWM_DISPLAYED_ADDRESS}
sleep 2
pm2 startup

#echo "Creating UpTimeKuma Service" | log
#cat << EOF > /etc/systemd/system/uptimekuma.service

#[Unit]
#Description=UpTime-Kuma Service
#After=network.target nss-lookup.target 

#[Service]
#StandardOutput=syslog
#StandardError=syslog
#SyslogIdentifier=uptimekuma
#ExecStart=/var/www/uptime-kuma/server/server.js
#Restart=always
#User=root
#Group=root
#Environment=PATH=/usr/bin/node
#Environment=NODE_ENV=production
#WorkingDirectory=/var/www/uptime-kuma/

#[Install]
#WantedBy=multi-user.target

#EOF

#echo "Enabling UpTime-Kuma Service" | log
#systemctl deamon-reload
#systemctl enable uptimekuma
#sleep 2
#systemctl start uptimekuma
#sleep 2
#waitOrStop 0 "Start UpTime-Kuma service failed"

echo "Adding descriptions" | log
descriptionAppend "UpTime-Kuma Directory: /var/www/uptime-kuma/"
descriptionAppend "Uptime-Kuma web UI: http://${CWM_DISPLAYED_ADDRESS}:3001"
descriptionAppend " "

tagScript success

exit 0
