#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist nginx.success

rootDir=$(rootDir)

echo "Setting Hostname" | log
hostnamectl set-hostname ${CWM_DOMAIN}

echo "Creating UpTime-Kuma Volume" | log
docker volume create uptime-kuma

echo "Creating NGINX VirtualHost" | log
cp $rootDir/tweaks/extras/uptime-kuma/uptime-kuma.conf /etc/nginx/sites-available/
sed -i "s/CWMDOMAIN/${CWM_DOMAIN}/g" /etc/nginx/sites-available/uptime-kuma.conf
ln -s /etc/nginx/sites-available/uptime-kuma.conf /etc/nginx/sites-enabled/
unlink /etc/nginx/sites-enabled/default
unlink /etc/nginx/sites-enabled/default-ssl
systemctl restart nginx
waitOrStop 0 "Restart nginx service failed"

echo "Starting UpTime-Kuma container" | log
systemctl restart docker
sleep 5
docker run -d --name uptime-kuma --restart unless-stopped \
	-p 3001:3001 -v "uptime-kuma:/app/data" "louislam/uptime-kuma:2"

echo "Enabling Docker Service & Restarting Services" | log
systemctl enable docker
sleep 2
systemctl restart nginx
sleep 2
waitOrStop 0 "Restart nginx service failed"

echo "Adding descriptions" | log
descriptionAppend "Uptime-Kuma Web UI: https://${CWM_DOMAIN}"
descriptionAppend " "

tagScript success

exit 0
