#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Installing Packages"
curl -o webmin-setup-repo.sh https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repo.sh
sh webmin-setup-repo.sh -f
waitOrStop 0 "Failed to setup Webmin repository"

echo "Installing Webmin App"
apt-get install webmin --install-recommends
waitOrStop 0 "Failed apt install Webmin"

echo "Adding descriptions" | log
descriptionAppend "Webmin Username: root"
descriptionAppend "Webmin Password: ${ADMINPASSWORD}"
descriptionAppend "Webmin UI: https://${CWM_DISPLAYED_ADDRESS}:10000"
descriptionAppend " "

tagScript success

exit 0

