#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

aptSourceList=/etc/apt/sources.list.d/zentyal.list
rootDir=$(rootDir)


echo "Modifying hostname to fit max 64 chars requirement" | log
savedHostname=$(hostname)
hostnamectl set-hostname ${savedHostname::32}

wget https://raw.githubusercontent.com/zentyal/zentyal/master/extra/ubuntu_installers/zentyal_installer_8.0.sh
chmod u+x zentyal_installer_8.0.sh
./zentyal_installer_8.0.sh

echo "ReInstalling Netplan" | log
installPackage netplan.io

echo "Creating admin user and disabling root" | log
useradd admin -s /bin/bash -m -g users -G sudo
chpasswd <<< "admin:${ADMINPASSWORD}"
-passwd -l root

echo "Fixing DNS Resolver" | log
sed '/gateway/a dns-nameservers 8.8.8.8 8.8.4.4' -i /etc/network/interfaces

echo "Ensuring conntrack modules are enabled" | log
echo ip_conntrack | sudo tee -a /etc/modules

echo "Starting resolve daemon " | log
systemctl enable systemd-resolved.service
waitOrStop 0 "Failed to enable resolved service"

echo "Adding descriptions" | log
descriptionAppend "Zentyal Admin URI: https://${CWM_SERVERIP}:8443"
descriptionAppend "Zentyal Admin User: admin"
descriptionAppend "Zentyal Admin Password: ${ADMINPASSWORD}"
descriptionAppend " "


tagScript success

exit 0
