#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi


add-apt-repository ppa:cherokee-webserver

apt-get install software-properties-common
apt install libev4 libjansson4 -y
wget -O - http://repo.zevenet.com/zevenet.com.gpg.key | apt-key add -
echo "deb http://repo.zevenet.com/ce/v5/ buster main" >> /etc/apt/sources.list.d/zevenet.list
apt-get update
wget -O nftlll.deb  http://ftp.debian.org/debian/pool/main/libn/libnftnl/libnftnl11_1.1.2-2_amd64.deb && dpkg -i nftlll.deb && rm -rf nftlll.deb
wget -O libnftables.deb http://ftp.debian.org/debian/pool/main/n/nftables/libnftables0_0.9.0-2_amd64.deb && dpkg -i libnftables.deb && rm -rf libnftables.deb
wget -O nftlb.deb http://archive.ubuntu.com/ubuntu/pool/universe/n/nftlb/nftlb_0.2-1_amd64.deb && dpkg -i nftlb.deb && rm -rf nftlb.deb
apt install -y zevenet


