#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
mkdir -p $rootDir/temp
appPath=/usr/local/zevenet
freePort="4444"

echo "Backup ip settings" | log
cp /etc/network/interfaces $rootDir/temp/interfaces

echo "Add zevenet repository" | log
# curl -fsSL http://repo.zevenet.com/zevenet.com.gpg.key | apt-key add -
curlDownload http://repo.zevenet.com/zevenet.com.gpg.key | log
waitOrStop 0
apt-key add zevenet.com.gpg.key
echo "deb http://repo.zevenet.com/ce/v5/ buster main" >> /etc/apt/sources.list.d/zevenet.list
apt update

echo "Install dependencies" | log
apt install software-properties-common libev4 libjansson4 -y
waitOrStop 0

echo "Install dependencies manually" | log

cd $rootDir/temp

# curl -Lo nftlll.deb  http://ftp.debian.org/debian/pool/main/libn/libnftnl/libnftnl11_1.1.2-2_amd64.deb  | log
curlDownload http://ftp.debian.org/debian/pool/main/libn/libnftnl/libnftnl11_1.1.2-2_amd64.deb nftlll.deb | log
waitOrStop 0
dpkg -i nftlll.deb 
rm -rf nftlll.deb

# curl -Lo libnftables.deb http://ftp.debian.org/debian/pool/main/n/nftables/libnftables0_0.9.0-2_amd64.deb | log
curlDownload http://ftp.debian.org/debian/pool/main/n/nftables/libnftables0_0.9.0-2_amd64.deb libnftables.deb | log
waitOrStop 0
dpkg -i libnftables.deb 
rm -rf libnftables.deb

# curl -Lo nftlb.deb http://archive.ubuntu.com/ubuntu/pool/universe/n/nftlb/nftlb_0.2-1_amd64.deb | log 
curlDownload http://archive.ubuntu.com/ubuntu/pool/universe/n/nftlb/nftlb_0.2-1_amd64.deb nftlb.deb | log 
waitOrStop 0
dpkg -i nftlb.deb 
rm -rf nftlb.deb

echo "Install zevenet gui and core" | log
apt install -y nftables zevenet zevenet-gui-ce | log
waitOrStop 0
sleep 5

echo "Tweaking configurations" | log
# Overwrite with backed up network config
cp $rootDir/temp/interfaces /etc/network/interfaces
# Configre zevenet virtual ip
sed -i 's/\;\;/\;'"${SERVERIP}"\;'/g' $appPath/config/if_eth0_conf
# Configure free port not blocked by system
sed -i "s/^server\!bind\!1\!port = [0-9]\+$/server\!bind\!1\!port = ${freePort}/" $appPath/app/cherokee/etc/cherokee/cherokee.conf
# Generate and apply random zapi key
zapi_key=`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 64 ; echo ''`
sed -i "s/\$zapikey=\"\"\;/\$zapikey=\"${zapi_key}\"\;/" $appPath/config/global.conf
# Restart server to apply changes
/etc/init.d/cherokee restart
sleep 5

echo "Adding descriptions" | log
descriptionAppend "Zevenet Admin URI: https://${SERVERIP}:${freePort}"
descriptionAppend "Zevenet Admin User: root"
descriptionAppend "Zevenet Admin Password: ${ADMINPASSWORD}"
descriptionAppend " "
descriptionAppend "Zevenet API Key: ${zapi_key}"
descriptionAppend "Zevenet API Reference: https://www.zevenet.com/zapidoc_ce_v4.0/"
descriptionAppend " "
descriptionAppend "Zevenet Configuration Directory: ${appPath}/config/"
descriptionAppend "Cherokee Server Configuration: ${appPath}/app/cherokee/etc/cherokee/cherokee.conf"
descriptionAppend " "

tagScript success

exit 0
