#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

rootDir=$(rootDir)
mkdir -p $(rootDir)/temp

echo "Backup ip settings" | log
cp /etc/network/interfaces $(rootDir)/temp/interfaces

echo "Add zevenet repository" | log
curl -fsSL http://repo.zevenet.com/zevenet.com.gpg.key | apt-key add -
# echo "deb http://repo.zevenet.com/ce/v5/ buster main" >> /etc/apt/sources.list.d/zevenet.list
echo "deb http://repo.zevenet.com/ce/v5/ buster main" >> /etc/apt/sources.list
apt-fast update
waitOrStop 0

echo "Install dependencies" | log
apt-fast install software-properties-common libev4 libjansson4 -y
waitOrStop 0

echo "Install dependencies manually" | log

cd $(rootDir)/temp

curl -Lo nftlll.deb  http://ftp.debian.org/debian/pool/main/libn/libnftnl/libnftnl11_1.1.2-2_amd64.deb  | log
waitOrStop 0
dpkg -i nftlll.deb 
rm -rf nftlll.deb

curl -Lo libnftables.deb http://ftp.debian.org/debian/pool/main/n/nftables/libnftables0_0.9.0-2_amd64.deb | log
waitOrStop 0
dpkg -i libnftables.deb 
rm -rf libnftables.deb

curl -Lo nftlb.deb http://archive.ubuntu.com/ubuntu/pool/universe/n/nftlb/nftlb_0.2-1_amd64.deb | log 
waitOrStop 0
dpkg -i nftlb.deb 
rm -rf nftlb.deb

echo "Install zevenet gui and core" | log
apt-fast install -y nftables zevenet zevenet-gui-ce | log
waitOrStop 0
sleep 5

echo "Copy backed up network config" | log
cp $(rootDir)/temp/interfaces /etc/network/interfaces

echo "Configre zevenet virtual ip" | log
sed -i 's/\;\;/\;'"${SERVERIP}"\;'/g' /usr/local/zevenet/config/if_eth0_conf

echo "Configure port 4444 not blocked by system" | log
sed -i "s/^server\!bind\!1\!port = [0-9]\+$/server\!bind\!1\!port = 4444/" /usr/local/zevenet/app/cherokee/etc/cherokee/cherokee.conf

# echo "Adding descriptions" | log

tagScript success

exit 0
