#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi


appPath=/home/zulip/deployments
rootDir=$(rootDir)

echo "Downloading Zulip from original repo" | log
cd $(mktemp -d)
curlDownload https://www.zulip.org/dist/releases/zulip-server-latest.tar.gz
waitOrStop 0 "File not downloaded from official sources"
tar -xzvf zulip-server-latest.tar.gz
waitOrStop 0 "Failed to extract archive"

echo "Installing Zulip Application"
./zulip-server-*/scripts/setup/install --self-signed-cert --email=${ADMINEMAIL} --hostname=${CWM_DOMAIN}

echo "Creating WebGUI URL"
cd $appPath
touch webgui.sh
touch url.log
cat << EOF > webgui.sh
#!/bin/bash

su -c "/home/zulip/deployments/next/manage.py generate_realm_creation_link" -s /bin/sh zulip | grep https

EOF

echo "Setting permissions"
chmod +x webgui.sh
./webgui.sh > url.log

descriptionAppend "Zulip application directory: ${appPath}/"
descriptionAppend "Zulip Web GUI:" | cat - /home/zulip/deployments/url.log
descriptionAppend " "
descriptionAppend "To create a new URL please use:"
descriptionAppend "su zulip"
descriptionAppend "/home/zulip/deployments/next/manage.py generate_realm_creation_link"

tagScript success

exit 0
