#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi


appPath=/home/zulip/deployments
rootDir=$(rootDir)

echo "Downloading Zulip from original repo" | log
cd $(mktemp -d)
curlDownload https://www.zulip.org/dist/releases/zulip-server-latest.tar.gz
waitOrStop 0 "File not downloaded from official sources"
tar -xzvf zulip-server-latest.tar.gz
waitOrStop 0 "Failed to extract archive"
echo "Installing Zulip Application" | log
./zulip-server-*/scripts/setup/install --self-signed-cert --email=${ADMINEMAIL} --hostname=${CWM_DOMAIN}
sleep 20
waitOrStop 0 "Failed to install Zulip"

webui=$(su -c "/home/zulip/deployments/next/manage.py generate_realm_creation_link" -s /bin/sh zulip | grep https)

echo "Configuring Nginx VirtualHost" | log

if [[ -f /etc/letsencrypt/live/${CWM_DISPLAYED_ADDRESS}/cert.pem ]]; then
      cp $rootDir/tweaks/extras/zulip/zulip.conf /etc/nginx/sites-available/
      unlink /etc/nginx/sites-enabled/zulip-enterprise
      mv /etc/nginx/sites-enabled/zulip-enterprise /etc/nginx/sites-enabled/
      sed -i "s/ServerDomain/${CWM_DOMAIN}/g" /etc/nginx/sites-enabled/zulip.conf
      sed -i '1i include /etc/zulip/nginx_sharding_map.conf;' /etc/nginx/sites-available/zulip.conf
      sed -i '/include \/etc\/zulip\/nginx_sharding.conf;/d' /etc/nginx/sites-available/zulip.conf
      sed -i "/ssl_certificate \/etc\/letsencrypt\/live\/${CWM_DISPLAYED_ADDRESS}\/cert.pem;/d; /ssl_certificate_key \/etc\/letsencrypt\/live\/${CWM_DISPLAYED_ADDRESS}\/privkey.pem;/d; /ssl_trusted_certificate \/etc\/letsencrypt\/live\/${CWM_DISPLAYED_ADDRESS}\/chain.pem;/d" /etc/nginx/sites-available/zulip.conf 
      sed -i -e ':a' -e 'N; $!ba' -e 's/\(server {[^}]*\)}/\1\n    ssl_certificate \/etc\/letsencrypt\/live\/'"${CWM_DISPLAYED_ADDRESS}"'\/fullchain.pem;\n    ssl_certificate_key \/etc\/letsencrypt\/live\/'"${CWM_DISPLAYED_ADDRESS}"'\/privkey.pem;\n    ssl_trusted_certificate \/etc\/letsencrypt\/live\/'"${CWM_DISPLAYED_ADDRESS}"'\/chain.pem;\n}/2' /etc/nginx/sites-available/zulip.conf     
fi

service nginx restart
waitOrStop 0 "Failed to restart NGINX"

descriptionAppend "Zulip application directory: ${appPath}/"
descriptionAppend "Zulip Web UI:${webui}"
descriptionAppend " "

tagScript success

exit 0

