#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

success=0
curlBaseParams=(--connect-timeout 10 --retry 3 --retry-connrefused --retry-delay 2 --max-time 30)
domains=(www.cloudwm.com www.google.com www.yahoo.com)

echo "Checking internet connectivity" | log

for domain in "${domains}"; do

    echo "Trying to fetch $domain" | log
    curl "${curlBaseParams[@]}" --url "http://$domain/" > /dev/null
    errorCode=$?

    if [ $errorCode -ne 0 ]; then

        echo "Failed." | log
        continue

    fi

    echo "Succeed." | log
    ((success++))

done

if [ $success -eq 0 ]; then 

    echo "Test passed $success times. Test Failed. (1)" | log 1
    tagScript failed
    exit 1

fi

echo "Test passed $success times. Test Passed. (0)" | log
tagScript success    
exit 0
