#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

ADMINPASSWORD=`cat $CWMCONFIGFILE  | grep password | cut -d= -f 2 | tr -d '[:space:]'`
