#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

appIndex=/var/www/html/index.html

if [ ! -f "$appIndex" ]; then

    echo "$appIndex file doesn't exist. Continuing"
    exit 99

fi

if grep -q "in progress" $appIndex; then

    echo "Removing $appIndex In Progress file." | log
    rm -f $appIndex 

    tagScript success
    exit 0

fi

# echo "$appIndex is not an In Progress file. Continuing" | log
# tagScript success
# exit 0