#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

if [ -d "/var/www/html" ];
then

    if [ ! -f "/var/www/html/index.html" ];
    then
        echo "Adding context Install in Progress to /var/www/html/index.html" | log
	useFiglet
	echo "<pre>" > /var/www/html/index.html
	bannerFiglet "Install in Progress\n Please Wait.\n" >> /var/www/html/index.html
        echo "Application and services installation is in progress, process will take a couple of minutes to complete \n Thank you for your patience.\n\n\n Refresh page within a couple of minutes for updated status." >> /var/www/html/index.html

        tagScript success

    else

	echo "index.html file exists. Skipping." | log

    fi
    exit 0

else

    echo "Web server directory doesn't exist, exiting." | log
    exit 1

fi
