#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

if [ -f "/etc/update-motd.d/98-install-in-progress" ]; 
then
    echo "Removing Install in Progress SSH Banner!" | log
    rm -rf /etc/update-motd.d/98-install-in-progress
    wall "Removing Install in Progress SSH Banner!"
    tagScript success
    exit 0
fi
