#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

inProgressMessage=/etc/update-motd.d/98-install-in-progress

if [ -f "$inProgressMessage" ]; then
    
    echo "Removing Install in Progress SSH banner" | log
    rm -f $inProgressMessage

    tagScript success
    exit 0
    
fi