#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

useFiglet

if [ -d "/var/www/html" ];
then

    if [ ! -f "/var/www/html/index.html" ];
    then
        echo "Adding context Install in Progress to /var/www/html/index.html" | log
	echo -e "Install in Progress\n Please Wait.\n" | figlet  -f big -c  > /var/www/html/index.html
        echo "Please refresh within a couple of min." >> /var/www/html/index.html

        tagScript success

    else

	echo "index.html file exists. Skipping." | log

    fi
    exit 0

else

    echo "Web server directory doesn't exist, exiting." | log
    exit 1

fi





