#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

if [ -f "/var/www/html/index.html" ]; 
then

    indexString=`cat /var/www/html/index.html | grep Application`

    if [ "$indexString" == 'Application*' ]; 
    then

        echo "Removing /var/www/html/index.html In Progress file." | log
        rm -f /var/www/html/index.html 

        tagScript success
        exit 0

    fi

else

    echo "/var/www/html/index.html file doesn't exist. Continuing"
    exit 99

fi
