#!/bin/bash

if [ -f "$CWMCONFIGFILE" ];
then

CONFIG=`cat $CWMCONFIGFILE`

IFS=$'\n'

for d in $CONFIG; 
do

    export `echo $d | cut -f 1 -d"="`="`echo $d | cut -f 2 -d"="`"

done

ADMINPASSWORD=$password
ADMINEMAIL=$email
ZONE=$zone
VMNAME=$name

WANNICIDS=`cat $CWMCONFIGFILE | grep ^vlan.*=wan-.* | cut -f 1 -d"=" | cut -f 2 -d"n"`
LANNICIDS=`cat $CWMCONFIGFILE | grep ^vlan.*=lan-.* | cut -f 1 -d"=" | cut -f 2 -d"n"`
DISKS=`cat $CWMCONFIGFILE | grep ^disk.*size=.* | wc -l`

fi

